### ISSUE TITLE
Space after element?

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#1762] opened 2017-02-15 20:21 UTC
##### Expected behavior.
Inserted elements have a space after to insert your cursor (for instance tables)
Would be preferable to press the down arrow to target a line below the element..

##### Actual behavior.
Inserted elements NO NOT have a space after to insert your cursor (for instance tables).
Have to awkwardly place cursor after table/element, which is hard to taget and half the time ends up click into the element/table

[![https://gyazo.com/0fcd3435f08cbe8df216ee3f6994f117](https://i.gyazo.com/0fcd3435f08cbe8df216ee3f6994f117.gif)](https://gyazo.com/0fcd3435f08cbe8df216ee3f6994f117)

[Summernote](http://summernote.org/) does this..
[![https://gyazo.com/3333e9b9977d163ac044995f8b266e44](https://i.gyazo.com/3333e9b9977d163ac044995f8b266e44.gif)](https://gyazo.com/3333e9b9977d163ac044995f8b266e44)

One problem is.. if you make custom elements, like below..
[![https://gyazo.com/88fc03b7901c6709205dee1ce7e26e9d](https://i.gyazo.com/88fc03b7901c6709205dee1ce7e26e9d.gif)](https://gyazo.com/88fc03b7901c6709205dee1ce7e26e9d)

How is it possible to give the user a space after the element?

#Try 1: Add a `&nbsp;` after the inserted elements

This works but it creates unwanted markdown (notice the jumpiness of editor)
[![https://gyazo.com/a1b900c170b14aa3133422ea488fbaf4](https://i.gyazo.com/a1b900c170b14aa3133422ea488fbaf4.gif)](https://gyazo.com/a1b900c170b14aa3133422ea488fbaf4)

This output is not very clean 
![image](https://cloud.githubusercontent.com/assets/17860864/22996454/afa2e342-f383-11e6-8cb5-d69d6621053f.png)

**Comment by Pyro979** [comment] 2017-04-19 16:25
I have a user reporting this issue with the tables. Focusing after AND before the table is basically impossible if all you have in the text area is the table.

**Comment by Pyro979** [comment] 2017-04-19 16:48
Some more input on this with regards to tables. In Chrome I can click before or after the table and properly focus on before or after the table. In IE or Firefox it is not appear possible to focus before or after the table by clicking on the outside of the table into the rich text area. I'll take a look at the code in a while.

@stefanneculai Should this be reclassified as a bug or should I open a separate ticket on the problem I just described?

**Comment by stefanneculai** [comment] 2017-05-23 12:41
Closing this as duplicate of #1762.

**Closed by stefanneculai** 2017-05-23 12:41 UTC
Labels: enhancement

**Comment by abologna-r7** [comment] 2017-07-11 19:51
How's this a duplicate of itself?

**Comment by stefanneculai** [comment] 2017-07-12 08:46
@abologna-r7 it should have been #1907. Sorry for the confusion.
