### ISSUE TITLE
Cell removes after pressing backspace

### ISSUE THREAD

**Issue by RaulPetrus** [froala/wysiwyg-editor#2820] opened 2018-05-16 10:38 UTC
Expected behavior.
Deleting all the characters one by one (using the backspace key) inserted in a cell from the table should not remove the cell

Actual behavior.
Deleting all the characters one by one (using the backspace key) inserted in a cell from the table removes the cell. Pressing backspace on a empty cell (without writing anything in it) does not remove the cell

Steps to reproduce the problem.
1. Go on https://www.froala.com/wysiwyg-editor
2. Insert a table in the text editor
3. Write something in any cell
4. Delete what is written using the backspace key
5. Observe that when the last character is deleted the cell is removed

OS.
Windows 10 Home 

Browser.
Google Chrome Version 66.0.3359.181

**Comment by SeanKendle** [comment] 2018-05-17 16:08
Also happens with DIVs. Similar to another already submitted bug request.

**Comment by stefanneculai** [comment] 2018-05-18 20:30
Duplicate of #2785

**Closed by stefanneculai** 2018-05-18 20:30 UTC
