### ISSUE TITLE
IE11 - Toolbar selection box On mouseover, the scroll jumps to the top. 

### ISSUE THREAD

**Issue by rhee80** [froala/wysiwyg-editor#3010] opened 2018-08-14 07:28 UTC
##### Expected behavior.
Hovering over paragraph format items has no effect on editor position.

##### Actual behavior.
Hovering over paragraph format items cause editor window to jump up to the top of editor content.

##### Steps to reproduce the problem.
1. Add content causing the editor to extend further than viewport
2. Scroll to the bottom of the content
3. Select Paragraph Format from the sticky nav and hover the cursor over an item
4. Editor window jump to the top
5. Not resolved in 2.8.5 version.

##### OS.
Server : Window Server 2016
Client : Window 10

##### Browser.
IE 11

**Comment by stefanneculai** [comment] 2018-08-14 17:41
Duplicate of https://github.com/froala/wysiwyg-editor/issues/2719.

**Closed by stefanneculai** 2018-08-14 17:41 UTC
