### ISSUE TITLE
Word Paste plugin doesn't handle images properly

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1806] opened 2017-03-07 19:54 UTC
##### Expected behavior.
Word paste should either imports images or omit them gracefully.

##### Actual behavior.
After pasting from a word doc with images, the image upload progress bar appears for a bit, and then a broken image plus some extra characters appear.

##### Steps to reproduce the problem.
1. Make sure "Word Paste" plugin is enabled.
2. Copy text from a word document with images. I used Sample_simple_application.docx from https://pct.wipo.int/DocConverter/sampleFiles.jsp
3. Paste text into froala editor

##### OS.
Windows 7 + Word 2013

##### Browser.
Chrome Latest (56.0.2924.87)

**Comment by dswitzer** [comment] 2017-03-08 22:15
This looks like a duplicate of #1785.

**Comment by stefanneculai** [comment] 2017-03-10 19:36
Closing as it is duplicate of #1820.

**Closed by stefanneculai** 2017-03-10 19:36 UTC
