### ISSUE TITLE
[Enterprise/Demo/Free Version] Froala 2.8.0 Numbered list/Ordered does not work.

### ISSUE THREAD

**Issue by haithngn** [froala/wysiwyg-editor#2758] opened 2018-04-24 04:15 UTC
##### Expected behavior.
During Numbered/Ordered edit mode when I hit return key Froala shoud create new line with new dot/number at the begin of the new line

##### Actual behavior.
Create a not/number then auto remove them and bring cursor back to the previous line.

##### Steps to reproduce the problem.

1. Numbered a sentence
Hit return key

##### OS.
iOS

##### Browser.
Apple Safari

**Comment by stefanneculai** [comment] 2018-04-24 04:26
Duplicate of https://github.com/froala/wysiwyg-editor/issues/2725

**Closed by stefanneculai** 2018-04-24 04:26 UTC
