### ISSUE TITLE
Extra line breaks appear on copy and paste

### ISSUE THREAD

**Issue by Zeblote** [froala/wysiwyg-editor#1738] opened 2017-02-03 23:36 UTC
##### Expected behavior.
Copying and pasting text that starts or ends with a line break produces the exact same result as a normal text editor, for example sublime text.

##### Actual behavior.
When copying text that ends (or starts) with a line break, it will insert two line breaks on paste.

##### Steps to reproduce the problem.
1. Make something like this in any froala editor:
![image](https://cloud.githubusercontent.com/assets/6764788/22612391/ad048508-ea70-11e6-86ef-4af05edaf071.png)
2. Select a line of text and the line break before it:
![image](https://cloud.githubusercontent.com/assets/6764788/22612415/ceb80940-ea70-11e6-840a-17b4d49390f2.png)
![image](https://cloud.githubusercontent.com/assets/6764788/22612424/dabdc086-ea70-11e6-9ca7-ef23ad0ea0f7.png)
3. Cut out the line and line break:
![image](https://cloud.githubusercontent.com/assets/6764788/22612438/01bbe0be-ea71-11e6-8758-4f129e3b8048.png)
4. Just paste it right back to where it was.
Current result:
![image](https://cloud.githubusercontent.com/assets/6764788/22612453/1aa637b4-ea71-11e6-9517-c22c46f5ecc4.png)
Expected result:
![image](https://cloud.githubusercontent.com/assets/6764788/22612482/41ffa7e6-ea71-11e6-9d94-2bff21f227a6.png)  
The same happens if the line break is at the end of the copied text.

##### Browser.
Windows 10, Chrome 56.0.2924.87 (64-bit)

**Comment by mukk85** [comment] 2017-02-06 07:13
This is probably related to the issue I am having as well. If you paste a block with single line breaks, it adds <p> tags around every block of text. Is there an option to use <br> instead when pasting?

**Comment by Zeblote** [comment] 2017-02-09 18:26
Why was this flagged as "enhancement"? It's a bug.

**Comment by stefanneculai** [comment] 2017-02-13 07:16
It is marked as an `enhancement` because when you copy from the browser, there is an empty paragraph copied because the selection is ending at the end of the previous paragraph.

**Comment by mukk85** [comment] 2017-02-13 08:02
That doesnt solve my problem when you paste text from a text editor with soft line breaks it adds p tags around every line. Anyway to solve that?

**Comment by stefanneculai** [comment] 2017-02-13 08:42
@mukk85 that is the intended behavior when you are using enter: `$.FroalaEditor.ENTER_P`. If you don't want them, then use `$.FroalaEditor.ENTER_BR`. https://www.froala.com/wysiwyg-editor/examples/enter

**Comment by Zeblote** [comment] 2017-03-07 03:11
I just tried out the 2.5.0 release and this is not fixed. Did you close the wrong issue?

**Comment by jwhitmarsh** [comment] 2018-01-05 10:36
Hi @stefanneculai - apologies for commenting on a closed issue, but I'd just be duplicating this in a new one. 

Is there any way around this at all? Or is there a way of differentiating between user inputted ENTER's and pasteCleanup ENTER's? Because at least if there was we could strip them out in post processing. 

At the moment the pasteCleanup ENTER's are causing problems because they resolve to carriage returns when the HTML is converted back to Word.

**Closed** 2018-01-25 17:53 UTC
Labels: bug

**Comment by alokissunny** [comment] 2018-05-15 09:32
is it still open as i am also facing this issue ?? please confirm
