### ISSUE TITLE
Code view doesn't respect heightMin/Max

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1260] opened 2016-05-14 02:28 UTC
##### Expected behavior.
Switching between wysiwyg view and code view will keep editor at the same size / height.

##### Actual behavior.
Entering code view makes editor/textarea larger than heightMin

##### Steps to reproduce the problem.
- http://jsfiddle.net/s46sbc1v/
- click code view icon

##### Browser.
Chrome

**Comment by philfreo** [comment] 2016-07-06 23:05
This still doesn't behave how I would expect. 

Go to http://jsfiddle.net/t4Lsqprp/ and toggle between regular & code view.

The code review becomes smaller than the wysiwyg view which is silly especially because the code view now requires a scrollbar to view it's content.

<img width="801" alt="screenshot 2016-07-06 19 05 30" src="https://cloud.githubusercontent.com/assets/97612/16637370/ab78e262-43ac-11e6-9a1e-58d4eb267b17.png">

**Comment by philfreo** [comment] 2016-07-07 17:36
I see you made a change, and that it works better now. But now if you look at empty content there's movement when toggling between them: http://jsfiddle.net/v08t7Lzd/

**Comment by stefanneculai** [comment] 2016-07-07 18:28
You mean cursoe location?

**Comment by philfreo** [comment] 2016-07-07 18:50
No, I mean the height of the entire editor gets larger slightly when switching to code. <img width="375" alt="screenshot 2016-07-07 14 49 37" src="https://cloud.githubusercontent.com/assets/97612/16665547/0b35bcac-4452-11e6-8dbc-ab4ce29fee21.png">

<img width="369" alt="screenshot 2016-07-07 14 49 31" src="https://cloud.githubusercontent.com/assets/97612/16665550/0e5d6a56-4452-11e6-88ea-d9ee8bcefc9e.png">

**Comment by philfreo** [comment] 2016-07-08 21:31
Better!

http://jsfiddle.net/umxv78vg/ is example now where you might actually want to code view to get bigger than the editor (up to `heightMax`, of course) so that you can edit the code without having to use the scrollbar unnecessary.

**Comment by philfreo** [comment] 2016-07-08 22:51
Similarly, if I start typing more HTML the textarea should autogrow like the editor does, up to heightMax

**Comment by philfreo** [comment] 2016-07-13 14:21
Looks good, thanks

**Comment by philfreo** [comment] 2016-07-13 15:08
Actually, starting in 3adca63 switching to the code view freezes my browser both in Firefox & Chrome. I can't reproduce it in a fiddle, but I can reliably reproduce in my app that on 3adca63 switching to code view freezes the browser, and reverting to b46598b removes the problem.

**Comment by stefanneculai** [comment] 2016-07-13 20:23
Can you provide any additional details about it? Maybe could you send us an email with a link to a page where to replicate this problem?

**Comment by stefanneculai** [comment] 2016-07-15 11:10
@philfreo We have tried several scenarios, but we cannot reproduce it. I believe you might have some CSS on the page which targets that textarea or it is a specific height when that is happening. Unfortunately, without a place where this is happening we cannot help. I am closing this until we get more details. Thank you.

**Closed by stefanneculai** 2016-07-15 11:10 UTC
Labels: bug

**Comment by philfreo** [comment] 2016-07-20 20:04
Definitely still an issue ever since 3adca63e4b03b84ea15b40c3e452f32c3d53bbe0 through current master. I can provide a link, but we'll need to be online at the same time for it. I've pinged you.
