### ISSUE TITLE
[3.1.0] `Uncaught TypeError: e is not a function` on fullscreen

### ISSUE THREAD

**Issue by lovelyelfpop** [froala/wysiwyg-editor#3803] opened 2020-01-18 02:08 UTC

**Comment by AndreaGProg** [comment] 2020-01-21 10:25
Same problem:

froala_editor.pkgd.min.js:7 Uncaught TypeError: e is not a function
    at f (froala_editor.pkgd.min.js:7)
    at Object.u [as toggle] (froala_editor.pkgd.min.js:7)
    at E.Bootstrap.callback (froala_editor.pkgd.min.js:7)
    at Object.n [as exec] (froala_editor.pkgd.min.js:7)
    at o (froala_editor.pkgd.min.js:7)
    at a (froala_editor.pkgd.min.js:7)
    at t (froala_editor.pkgd.min.js:7)
    at E.Bootstrap.c (froala_editor.pkgd.min.js:7)
    at r (froala_editor.pkgd.min.js:7)
    at HTMLButtonElement.<anonymous> (froala_editor.pkgd.min.js:7)

**Comment by skullacy** [comment] 2020-01-28 07:24
Same problem too.

**Comment by kelvinmusselli** [comment] 2020-01-30 20:00
Me too have this problem :(

**Comment by HerrDietz** [comment] 2020-02-04 09:37
Same Problem here

**Comment by joscht** [comment] 2020-02-17 15:48
Got the same problem with version 3.1.0. Unfortunately it's not just an error in the console, but the editor doesn't fill the complete screen.
If I don't override the toolbarButtons in the froala options, I still see the error in the console, but the editor fills the complete screen (which is not an option for us though because we want to override the toolbarButtons).

Any updates on this issue? We're kinda blocked due to this issue.

**Comment by krissce** [comment] 2020-02-18 13:19
Got the same full screen issue and error in console with Froala 3.1 when toolbarButtons is set to some custom value.

**Comment by ddoe8** [comment] 2020-02-20 12:24
Having issues with this bug too.

**Comment by herumtreiber** [comment] 2020-02-21 13:36
+1

**Comment by RantoniainaHairun** [comment] 2020-03-09 12:31
+1

**Comment by hashina** [comment] 2020-03-09 12:36
+1

Can you fix this asap guys?

**Comment by HerrDietz** [comment] 2020-03-13 12:02
I wonder why so little happens here. The bug prevents us from replacing squire with froala. 

Even in the rather minimal jsfiddle demo https://jsfiddle.net/froala/pruvo6j8/3/ the bug is reproducible (Chrome 80.0.3987.132). All you have to do is toggling fullscreen. 

Please have look into it.

**Comment by dejanmartinovic** [comment] 2020-03-25 21:48
The fix will be available in the next editor release. However, as the fix has already been added to the master branch, you can access it from here: `https://cdn.jsdelivr.net/gh/froala/wysiwyg-editor@master/js/froala_editor.pkgd.min.js  ` 
https://jsfiddle.net/dejan_m/Lha56d3p/365/.

**Comment by trainbolt** [comment] 2020-04-04 02:44
If anyone is interested the fix is pretty simple after tearing the code apart in 3.1.0

### In plugins.pkgd.min.js:

**Find**
`e=r.opts,o=e.height,e((t=r.opts,s=t.heightMax,t))((a=r.opts,l=a.z_index,a))`

**Replace with:**
`o=r.opts.height,s=r.opts.heightMax,l=r.opts.zIndex`

### In fullscreen.min.js:

**Find**
`e=s.opts,i=e.height,e((t=s.opts,a=t.heightMax,t))((r=s.opts,l=r.z_index,r))`

**Replace with:**
`(i = s.opts.height),(a = s.opts.heightMax),(l = s.opts.zIndex),`

The e() function is obviously incorrect whether that has anything to do with how the code was minimized or if it was an error in programming I'm not sure, but I am sure this fixes the issue.

Taking this long to fix an issue this small is completely ridiculous!

**Comment by robertvanhoesel** [comment] 2020-06-08 10:43
This bug has apparently been fixed in 3.1.1, but not updated here.

> Version 3.1.1   
> Release Date: Feb 23, 2020
> - Fullscreen bug fixed
> - FontFamily/fontSize output fixed
> - Numerous performance improvements

**Comment by onedotover** [comment] 2020-08-05 17:29
I'm on 3.2 and this does not seem to be fixed.

**Comment by shah20** [comment] 2020-10-27 08:48
+1

**Comment by dejanmartinovic** [comment] 2020-10-27 13:18
@robertvanhoesel @onedotover @shah20 The `Uncaught TypeError: e is not a function` on fullscreen - the problem is solved in version 3.1.1. 
STRs:
Open this fiddle: https://jsfiddle.net/dejan_m/og0hxf2t/
Click the Fullscreen button
Check the console
result=> no errors

**Comment by dejanmartinovic** [comment] 2020-10-27 13:20
> If anyone is interested the fix is pretty simple after tearing the code apart in 3.1.0
> 
> ### In plugins.pkgd.min.js:
> **Find**
> `e=r.opts,o=e.height,e((t=r.opts,s=t.heightMax,t))((a=r.opts,l=a.z_index,a))`
> 
> **Replace with:**
> `o=r.opts.height,s=r.opts.heightMax,l=r.opts.zIndex`
> 
> ### In fullscreen.min.js:
> **Find**
> `e=s.opts,i=e.height,e((t=s.opts,a=t.heightMax,t))((r=s.opts,l=r.z_index,r))`
> 
> **Replace with:**
> `(i = s.opts.height),(a = s.opts.heightMax),(l = s.opts.zIndex),`
> 
> The e() function is obviously incorrect whether that has anything to do with how the code was minimized or if it was an error in programming I'm not sure, but I am sure this fixes the issue.
> 
> Taking this long to fix an issue this small is completely ridiculous!

The mentioned issue is not related to this ticket

**Comment by VuyyuruRaj** [comment] 2021-11-16 08:54
"Hi I'm Raj the Product Marketing Manager for Froala - would love your feedback.
And BTW checkout the latest V4.0.6 ( https://bit.ly/3kHelBE ) - "The most Performant Version" . Thanks!

**Comment by ilyaskarim** [comment] 2022-06-29 18:44
Fixed in V3.1.1 https://froala.com/wysiwyg-editor/changelog/#3.1.1

**Closed by ilyaskarim** 2022-06-29 18:44 UTC
Labels: bug, version 3
