### ISSUE TITLE
Lists - Can't select the Default list once another is set

### ISSUE THREAD

**Issue by loxiw** [froala/wysiwyg-editor#3203] opened 2018-12-12 08:50 UTC
##### Expected behavior.
When a custom OL/UL is setted and I select the "Default" option, "Default" is set

##### Actual behavior.
Nothing happens

##### Steps to reproduce the problem.
https://www.froala.com/wysiwyg-editor/examples/list-style-type
· Select any OL/UL (not the default)
· Select the "Default"

##### OS.
Arch Linux

##### Browser.
Chromium

**Comment by stefanneculai** [comment] 2018-12-13 11:52
Duplicate of https://github.com/froala/wysiwyg-editor/issues/3171

**Closed by stefanneculai** 2018-12-13 11:52 UTC
