### ISSUE TITLE
Throwing exception on copy or cut

### ISSUE THREAD

**Issue by moinism** [froala/wysiwyg-editor#1402] opened 2016-07-12 16:04 UTC
##### Expected behavior.
It should not throw an exception when copying or cutting from editor.

##### Actual behavior.
It shows a `Uncaught TypeError: Cannot read property 'get' of undefined` error in console when trying to copy or cut from editor.

##### Steps to reproduce the problem.
[Visit the link](https://www.froala.com/wysiwyg-editor), keep your devtools (console tab) open and try copying or cutting text from demo editor.
On Firefox is says `TypeError: mt is undefined`.

##### OS.
Windows 10, macOS

##### Browser.
Chrome, Opera, Firefox

**Comment by stefanneculai** [comment] 2016-07-12 16:13
Duplicate of #1401

**Closed by stefanneculai** 2016-07-12 16:13 UTC
