### ISSUE TITLE
Editor is adding &nbsp;( non-breaking space)  for list items <li> which breaks the layout.

### ISSUE THREAD

**Issue by sumisha** [froala/wysiwyg-editor#471] opened 2015-03-11 10:22 UTC
If we add Bulleted List using froala editor,  it replaced each space of the content with &nbsp; which is not allowing the content to get wrap and so the page style breaks. How can I solve this issue.

sample content:
`&nbsp;For&nbsp;the&nbsp;courseware,&nbsp;we&nbsp;obviously&nbsp;want&nbsp;to&nbsp;bring&nbsp;onboard&nbsp;the&nbsp;best&nbsp;minds&nbsp;in&nbsp;the&nbsp;arena,&nbsp;to&nbsp;help&nbsp;us&nbsp;build&nbsp;engaging&nbsp;content&nbsp;that&nbsp;helps&nbsp;people&nbsp;quickly&nbsp;get&nbsp;started&nbsp;with&nbsp;solving&nbsp;problems&nbsp;in&nbsp;science&nbsp;with&nbsp;open-source.&nbsp;`

**Comment by stefanneculai** [comment] 2015-03-11 10:23
The issue is fixed on the master version.

**Closed by stefanneculai** 2015-03-11 10:23 UTC

**Comment by sumisha** [comment] 2015-03-11 10:25
When is the next version getting released with this fix?

**Comment by stefanneculai** [comment] 2015-03-11 10:26
Sorry, but we don't have a specific date for it yet. Most probably during April.

**Comment by bradleygauthier** [comment] 2015-04-07 21:32
How do we fix this in the mean time? I tried the master and it still created the non breaking space. It appears to only happen when the text is pasted into the li.
