### ISSUE TITLE
Issue on mobile device when enter new line or adding new line (iphone, android)

### ISSUE THREAD

**Issue by opan** [froala/wysiwyg-editor#2754] opened 2018-04-22 14:48 UTC
##### Expected behavior.
When adding new line in mobile device / mobile screen, it should be working like we do in desktop screen and also we can click the toolbar buttons in mobile device

##### Actual behavior.
When adding new line in mobile device/ mobile screen, there is some glitch appear (cursor like reverted after we press enter key/ new line). You can check the gif I provide. Also we can't click the toolbar.

##### Steps to reproduce the problem.

I don't set up a fiddle yet to how to reproduce these problems, but you can see in this GIF below.
Each browser gives us different issues. I can't click the toolbar on Safari in mobile device mode, but in Chrome, I could click it.

![enter-key-bugs-froala-chrome-iphone678 mov](https://user-images.githubusercontent.com/7332483/39096158-4f8da202-4676-11e8-9282-1be0dff7ec33.gif)

![enter-key-bugs-froala-safari-iphone8 mov](https://user-images.githubusercontent.com/7332483/39096165-74f3cf3a-4676-11e8-8c16-8cf77257013f.gif)

![working-sample-desktop-safari mov](https://user-images.githubusercontent.com/7332483/39096169-80da29de-4676-11e8-917e-91825e8795f6.gif)

##### OS.
(OS name and version here)
OS X Sierra

##### Browser.
(Browser name an version here)
Chrome: Version 66.0.3359.117 (Official Build) (64-bit)
Safari: Version 11.1 (12605.1.33.1.3)

**Comment by stefanneculai** [comment] 2018-04-22 15:00
Duplicate of #2725

**Closed by stefanneculai** 2018-04-22 15:00 UTC
Labels: bug

**Comment by opan** [comment] 2018-04-22 15:16
Hi @stefanneculai thank you very much for the super fast response! 

Okay, right now I know that other people have a similar issue with adding a new line with OL or UL. But can you help me about us unable to click the toolbar on mobile device simulator in Safari browser? It looks only in the Safari I can't click the toolbar but not in mobile device simulator on Chrome.

Thanks
