### ISSUE TITLE
korean language issue

### ISSUE THREAD

**Issue by open2** [froala/wysiwyg-editor#1545] opened 2016-10-01 03:31 UTC
##### Expected behavior.

I write "찟" 

![000](https://cloud.githubusercontent.com/assets/2640011/19011512/cc48d51e-87d2-11e6-85ae-93839a54cfa6.PNG)
##### Actual behavior.

"찟" did not appeared. no output

![0_](https://cloud.githubusercontent.com/assets/2640011/19011514/de0c83ae-87d2-11e6-8a9e-b258b9b13416.PNG)
##### Steps to reproduce the problem.

write "찟" in Korean.
##### OS.

windows 7
##### Browser.

chrome

**Comment by stefanneculai** [comment] 2016-10-05 07:43
Could you please let us know what keys are you pressing on a qwerty keyboard? Also, are you able to reproduce it on our website?

**Comment by open2** [comment] 2016-10-06 05:04
찟 -> (in Korean language) shift+w -> l (small L not large i) -> t

2016-10-05 16:43 GMT+09:00 Stefan Neculai <notifications@github.com>:

**Comment by stefanneculai** [comment] 2016-10-14 10:10
We just tested this and it is not happening with the Github master. @largeden could you provide some insights?

**Comment by largeden** [comment] 2016-10-14 14:47
@open2 @stefanneculai 

I can not reproduce the problem.
(Sorry. can not Windows 7 test. but there is no problem in Windows 10.)

- froala v2.3.4
- chrome
- windows 10

**Comment by open2** [comment] 2016-10-15 00:53
I have no windows 10. -..-...

in MySQL DB, inserted like this.
<p>&nbsp;찟</p><p><br></p>

2016-10-14 23:47 GMT+09:00 Ji-Yeon Choi <notifications@github.com>:

**Comment by stefanneculai** [comment] 2016-11-08 14:13
I am closing this because we cannot reproduce the problem. @open2 if you could get back to us with enough details to reproduce it, then we'll open it again and fix it.

**Closed by stefanneculai** 2016-11-08 14:13 UTC
Labels: cannot-reproduce
