### ISSUE TITLE
Inline Froala Menu - Centres itself when empty <p>'s are added

### ISSUE THREAD

**Issue by daniellevautier** [froala/wysiwyg-editor#1742] opened 2017-02-06 15:22 UTC
##### Expected behavior.
When highlighting copy that has a double paragraph (e.g. p  br  p ) the inline editor should ignore the width of the empty p 

##### Actual behavior.
When highlighting copy that has a double paragraph the inline editor takes into consideration the width of the empty p tag causing it's position to be way off.

##### Steps to reproduce the problem.
Use inline WYSIWYG editor type and press enter twice then type again. Now highlight the copy.
Video: https://cl.ly/3B0W0536153H

##### OS.
Windows 10

##### Browser.
Chrome

**Comment by stefanneculai** [comment] 2017-02-09 09:13
Duplicate of https://github.com/froala/wysiwyg-editor/issues/1572#issuecomment-259158876.

**Closed by stefanneculai** 2017-02-09 09:13 UTC
