### ISSUE TITLE
Issue #625 has re-surfaced in version 2.9.3

### ISSUE THREAD

**Issue by platomedical** [froala/wysiwyg-editor#3336] opened 2019-03-05 02:20 UTC
https://github.com/froala/wysiwyg-editor/issues/625

Note: If text is present in the text area the three formats can be selected at the same time

Steps to reproduce:

Click on the bold format while Froala text area is empty
Click italic option
Click underlined option
Clicked striked through format option

**Actual result:**
4. The the three format option cannot be selected at the same time if there is no text in Froala’s textarea

**Expected results:**
4. All three options should be selectable at the same time even if no text is present in the text area

**Comment by stefanneculai** [comment] 2019-03-06 12:26
Seems like duplicate of #3334.

**Closed by stefanneculai** 2019-03-06 12:26 UTC
