### ISSUE TITLE
Bullet not synchronized with font size.

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#3234] opened 2019-01-13 23:56 UTC
##### Expected behavior.
(Describe expected behaviour here)
If you specify a bullet and change the font size, the bullet size must also change according to the font size.

##### Actual behavior.
(Describe actual behaviour here)
The bullet size is fixed even if you change the font size.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
1. Enter a sentence in editor.
2. Add a bullet to the sentence.
3. Set the font of the sentence to large.

##### OS.
(OS name and version here)
Windows 7

##### Browser.
(Browser name an version here)
IE11 & Chrome 71.0

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by stefanneculai** [comment] 2019-01-15 15:54
Duplicate of https://github.com/froala/wysiwyg-editor/issues/1962

**Closed by stefanneculai** 2019-01-15 15:54 UTC
