### ISSUE TITLE
Deleting last character on a line makes cursor jump to previous line

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#4064] opened 2020-10-06 13:02 UTC
##### Expected behavior.
When deleting the last character on a line, the cursor remains on that line.

##### Actual behavior.
When deleting the last character on a line, the line is removed and cursor jumps up to the end of the previous line.

##### Steps to reproduce the problem.
1. Initialize the editor with enter set to ENTER_BR option
2. Delete the last character on a line

The issue can be reproduced by deleting the characters on the last line in this fiddle:

https://jsfiddle.net/aytqsodw/

##### Editor version.
3.2.2

##### OS.
MacOS 10.15.6

##### Browser.
Chrome 85.0.4183.121 (Official Build) (64-bit)

**Comment by arthurfanti** [comment] 2021-01-28 17:26
Having the same issue here, @felskov 
Did you find any solution?

**Comment by felskov** [comment] 2021-01-28 19:22
No unfortunately not. We're still waiting for an official fix.

**Comment by luizeboli** [comment] 2021-03-02 12:24
Same issue here, thinking in a solution...

**Comment by dcsaszar** [comment] 2021-11-29 06:43
FYI I tried the fiddle https://jsfiddle.net/aytqsodw/ on the latest MacOs+Chrome and can't reproduce the cursor jump.
The issue I see is that the cursor jumps to the left of the space before the deleted character, and on the second backspace nothing happens.

With 4.0.7, it works for me.

**Comment by ilyaskarim** [comment] 2022-11-23 18:32
Fixed in V4.0.15 https://froala.com/wysiwyg-editor/changelog/#4.0.15

**Closed by ilyaskarim** 2022-11-23 18:32 UTC
