### ISSUE TITLE
Cannot select and format multiple cells at a time

### ISSUE THREAD

**Issue by kmacampbell** [froala/wysiwyg-editor#1527] opened 2016-09-20 17:05 UTC
##### Expected behavior.

Should be able to highlight multiple cells with a mouse drag and have ability to manipulate (e.g., apply formatting, delete content, copy) all of them at once. 
##### Actual behavior.

When selecting multiple cells with a mouse drag, all formatting controls within the toolbar become disabled, and keyboard shortcuts (e.g., copy, delete) do not work either. As a result, individual cells need to be highlighted and manipulated individually, which is very cumbersome. See attached gif. (Shows steps required to bold top row of a table.)
##### Steps to reproduce the problem.

1) Insert a table which contains 2+ columns and/or rows
2) Select multiple cells by clicking/dragging mouse
3) The toolbar controls become disabled and keyboard shortcuts (delete, copy) don't work.
##### OS.

Windows 10 pro
##### Browser.

Chrome 53.0.2785.116 m (64-bit)

![froala_cannot_format_multiple_cells](https://cloud.githubusercontent.com/assets/22326825/18680666/b8fdb5fe-7f32-11e6-9787-69fb1bd93de4.gif)

**Comment by ravitejabommakanti** [comment] 2017-04-13 13:35
Is there any workaround to select multiple cells of table and format/apply styles.

**Comment by stefanneculai** [comment] 2017-07-20 12:05
@kmacampbell @ravitejabommakanti unfortunately, this is a limitation because of the way V2 was designed and cannot be achieved in the current version. For now we'll leave it as a `wontfix`.

**Comment by SimonLuckenuik** [comment] 2017-10-31 19:07
This is a must have to have a Microsoft Word like experience. Is this in your backlog?

**Comment by stefanneculai** [comment] 2017-11-03 09:52
@SimonLuckenuik it is going to be implemented eventually, however I cannot provide an ETA.

**Comment by stefanneculai** [comment] 2018-03-05 14:48
I am closing this and marking as a `feature-request` as it is not possible to implement it in V2, but will be addressed in the next version.

**Closed by stefanneculai** 2018-03-05 14:48 UTC
Labels: wontfix

**Comment by nodefiend** [comment] 2018-04-27 04:33
@stefanneculai 

Greetings! 

Our application is using Froala, we also have a paid business license. 

Our users rely heavily on table creation, and the ability to format multiple cells at the same time, right now we have several users asking to be able to modify the text in multiple selected cells.

The last note on this issue was that it was going to be in the next release.

We recently upgraded our app to 2.81 and I did not see in the change log , and I am still unable to format the text in multiple cells. 

Was wondering if you could provide an update on the status of this, or maybe let us know if we missed it in the patch notes?

thanks 

ken

**Comment by coding-bird** [comment] 2020-07-08 12:45
@stefanneculai Can't see this fix of this issue even in version 3, I think it's basic requirement in order to work with tables, to be able to select, copy, paste tables using mouse drag.
Do you have any ETA around this ?

**Comment by Hiaslafson** [comment] 2022-11-17 13:59
Are there any changes on this topic? We just got the license but think of changing to another editor. We built a workaround which is just not nice.

Thanks for helping

**Comment by mwntt** [comment] 2024-03-29 12:31
Are there any updates on the feature?

**Comment by bryanakitchen** [comment] 2024-06-25 19:36
Looks like the only option is creating [custom table cell styles](https://froala.com/wysiwyg-editor/examples/table-cell-styles/).
