### ISSUE TITLE
Formatting `contenteditable` maximum call stack

### ISSUE THREAD

**Issue by jhchill666** [froala/wysiwyg-editor#4370] opened 2021-11-25 09:09 UTC
##### Expected behavior.
When applying arbitrary formatting to an element with `contenteditable="false"`, the element should be styled accordingly

##### Actual behavior.
When applying arbitrary formatting to an element with `contenteditable="false"`, the element is not styled, and we witness a `Uncaught RangeError: Maximum call stack size exceeded` error in the console

##### Steps to reproduce the problem.

https://jsfiddle.net/upgnvekj/2/

Highlight the text in the editor, and try and make it **bold** or any other format.  You'll see maximum call stack error in the console

##### Editor version.
This is using `v4.0.7`, but the problem seems to exist on all `v4.x.x` versions.

##### OS.
NA

##### Browser.
Chrome 

##### Recording.
NA

**Comment by MeghashreeAP** [comment] 2022-01-20 13:59
Thanks for your feedback.
This issue is not reproducible or have been found to be fixed on the latest Froala release v4.0.8.
Can you please upgrade and check?

**Comment by jhchill666** [comment] 2022-01-20 15:00
Just checked with the jsfiddle I provided above, and it is still erroring

**Comment by decherneyge** [comment] 2022-01-24 20:43
@MeghashreeAP I think I see where the error is coming from if you search in the minified file for this:
`if("SPAN"===l.tagName)return v(l.firstChild,t,n),!1;if(l.tagName&&l.hasAttribute("contenteditable")&&"false"===l.getAttribute("contenteditable"))return void`

I believe the second if block there should be executed before the first one since it has a more specific condition than just "is span tag"

This is causing my org a bit of pain. I am sort of able to get around it by changing my contenteditable=false tag to a div styled with display:inline-block but its less than ideal.

**Comment by decherneyge** [comment] 2022-02-01 20:31
@jhchill666 Updating to 4.0.9 that dropped today resolved this for me

**Comment by ilyaskarim** [comment] 2022-09-07 23:58
Fixed in V4.0.9

**Closed by ilyaskarim** 2022-09-07 23:58 UTC
