### ISSUE TITLE
A search mechanism within Image Manager is vital

### ISSUE THREAD

**Issue by molidort** [froala/wysiwyg-editor#2663] opened 2018-03-18 12:17 UTC
When dealing with a large amount of images, the manager is useless.
A search mechanism should be added urgently.
Just add a simple INPUT at the upper line, look for tags and\or names. 
Otherwise it is unusable and inefficient at all.

BTW, Why is the manager only for images? we need it also for videos.
Thanks.

**Comment by stefanneculai** [comment] 2018-03-19 10:42
Duplicate of #2230.

@molidort thanks for the request. It is on our TODO list, however, we haven't got to implement it yet.

**Closed by stefanneculai** 2018-03-19 10:42 UTC
Labels: feature-request

**Comment by molidort** [comment] 2018-03-19 11:07
Thanks.
Is there an estimate when such a thing might be ready?
The search must be either on the server or on the client, according to a parameter.

**Comment by stefanneculai** [comment] 2018-05-14 19:18
@molidort unfortunately, we don't have an ETA for this.

**Comment by heinydo** [comment] 2021-11-04 11:38
Has this feature not been followed up on? 
We have the same problem as described above. Due to a large number of images, the Image manager is useless.

A simple search function would fix the problem.
