### ISSUE TITLE
Text selection is not working properly

### ISSUE THREAD

**Issue by jithinrajpr** [froala/wysiwyg-editor#3886] opened 2020-04-22 11:08 UTC
##### Expected behavior.
When we try to select text it should select it even for multiple lines.

##### Actual behavior.
When we try to select text it get un-selected.

##### Steps to reproduce the problem.
This issue only came to me when I try to select the text which is inside a `table` which is inside another `table`,  I am not sure if this issue occurs in any other cases. A [jsFiddle] for you to check. (https://jsfiddle.net/jithinrajpr7/ztjbguxy/)

##### Editor version.
The version of the editor is 3.1.1 but this also works the same in 3.1 also

##### OS.
MacOS Mojave 10.14.6

##### Browser.
Chrome Version 80.0.3987.163 

##### Recording.
https://drive.google.com/file/d/1Nxn4dB7XHvogXU3MyQBvmDZM3vU_wZ2x/view

**Comment by jithinrajpr** [comment] 2020-07-07 11:32
@stefanneculai  will you help me with this. This issue occurs in every inline element inside multiple tables. please do help me.

**Comment by KeanuFerreira** [comment] 2020-09-24 13:30
We are encountering the same Problem. Any fixes?

**Comment by KeanuFerreira** [comment] 2021-07-27 13:02
@jithinrajpr this seems fixed in 3.2.7. I guess Issues arent being watched.

**Comment by ilyaskarim** [comment] 2022-06-30 23:02
The issue is already being fixed in V3.2.3: https://froala.com/wysiwyg-editor/changelog/#3.2.3

**Closed by ilyaskarim** 2022-06-30 23:02 UTC
