### ISSUE TITLE
The height of iframe is zero in Firefox

### ISSUE THREAD

**Issue by kartikbb** [froala/wysiwyg-editor#1861] opened 2017-03-21 12:30 UTC
##### Expected behavior.
Height should be same as minimum height

##### Actual behavior.
Height is zero

##### Steps to reproduce the problem.
Initialize a textarea with heightMin of say 100 and iframe = true. The textarea is bound to a model (angularjs) with value as empty string or null. Notice, the textarea is rendered with no place enter text. If you inspect the code in browser, the generated iframe has a height of 0.
https://www.screencast.com/t/ZtK5W99YVx
https://www.screencast.com/t/AJq4b1yR 

##### OS.
Windows 10

##### Browser.
Firefox 52.0.1

**Comment by stefanneculai** [comment] 2017-03-21 15:34
@kartikbb are you having the editor hidden initially? If so, then it is a duplicate of https://github.com/froala/wysiwyg-editor/issues/1449.

**Closed** 2017-03-24 11:45 UTC
