### ISSUE TITLE
Bold Shortcut Left Justifies Text on Demo Site

### ISSUE THREAD

**Issue by gonzalotudela-hub** [froala/wysiwyg-editor#4290] opened 2021-07-15 15:55 UTC
##### Expected behavior.
I expect that when I select text and try to unbold it with the shortcut CMD + B, that the text unbolds

##### Actual behavior.
Instead, the text left justifies after I press CMD + B twice

##### Steps to reproduce the problem.
- Go to https://froala.com/
- Click WYSIWYG Editor in the menu
- Inside the demo, put your cursor at the beginning of all the text (to the left of the arrow pointing right)
- Hit enter twice to give some line breaks
- Go to the top of the paragraphs and write a new sentence
- Select the line from right to left using the keyboard shortcuts SHIFT + CMD + Left Arrow
- Use the keyboard shortcut CMD + B to bold the text
- Use the keyboard shortcut CMD + B to unbold the text, and watch it left justify instead

##### Editor version.
Froala 4.0.3

##### OS.
macOS Big Sur 11.4 (20F71)

##### Browser.
Google Chrome Version 91.0.4472.114 (Official Build) (arm64)

##### Recording.
https://drive.google.com/file/d/1GU_Q1UXiLv7OWjGBTFDybNRkSMtxZdVW/view?usp=sharing

**Comment by AkshayCM** [comment] 2022-01-20 10:57
Thank you for your feedback. The request has been reported to the product management team for evaluation and consideration for an upcoming release.

**Comment by ilyaskarim** [comment] 2022-11-30 17:59
The issue is already being fixed in V4.0.13: https://froala.com/wysiwyg-editor/changelog/#4.0.13

**Closed by ilyaskarim** 2022-11-30 17:59 UTC
