### ISSUE TITLE
Pressing external Insert link button popup points to empty space to the right

### ISSUE THREAD

**Issue by SagarKharche** [froala/wysiwyg-editor#2916] opened 2018-06-26 12:47 UTC
Expected behavior.
Pressing external Insert link button popup points to selection

Actual behavior.
Pressing external Insert link button popup points to empty space to the right

Steps to reproduce the problem.
https://jsfiddle.net/jnv4x1jo/156/

select some text within an editor
Press external Insert link button

OS.
any

Browser.
google chrome latest

**Comment by stefanneculai** [comment] 2018-07-05 11:57
@SagarKharche we couldn't reproduce it. Do you think you could make a jsFiddle?

**Comment by SagarKharche** [comment] 2018-07-05 12:13
@stefanneculai  I have added the fiddle link(https://jsfiddle.net/jnv4x1jo/156/). Select the text and click on insert link external button added in fiddle. Hope this will help.

**Comment by stefanneculai** [comment] 2018-07-12 09:54
Closing this as it looks fine to me and haven't got any further details.

**Closed by stefanneculai** 2018-07-12 09:54 UTC
Labels: cannot-reproduce, waiting-details
