### ISSUE TITLE
How to prevent popup closing

### ISSUE THREAD

**Issue by Qlipoth** [froala/wysiwyg-editor#1144] opened 2016-03-22 11:13 UTC
##### Expected behavior.
popup closing by clicking inside the popup area
https://s14.postimg.org/4453b83mp/bug.gif
##### Actual behavior.
popup closing only by clicking "close" button

**Comment by stefanneculai** [comment] 2016-03-22 11:59
Please make a jsFiddle for it.

**Comment by stefanneculai** [comment] 2016-03-30 09:46
I am closing this due to lack of information to reproduce it.

**Closed by stefanneculai** 2016-03-30 09:46 UTC
Labels: cannot-reproduce

**Comment by lym8356** [comment] 2024-02-22 01:06
I think this feature is not supported, the popup closes when I click outside of the popup, is there way to make it stay opened and only close it when you click on a close button?
