### ISSUE TITLE
improvement idea of line_breaker plugins.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#867] opened 2015-10-20 07:03 UTC
hello. :)

The last time, Line Break was a problem occurs outside the editor.
#786 

So you had to fix table.min.js. But, I think that the cause of the problem in line_breaker.js

I declare the following values, and looked to run the froala editor.

```javascript
$('#edit').froalaEditor({ lineBreakerTags: ['table', 'div'] });
```

Editor outside as well, code_view screen can be seen that in the Line Break occurs.
I think the line_breaker plugin should be carried out only in the editor content.

I solved the problem by improving the code below. (Not a good way.)

```javascript
// line_breaker.min.js
/*
* Check if tag is in the line breaker list.
* Returns the tag from the line breaker list or false if the tag is not in the list.
*/
function _checkTag (tag) {
	if (tag) {
	var $tag = $(tag);

	var $frview = $tag;
	while(!$frview.hasClass('fr-view') && $frview[0].tagName != 'HTML') {
		$frview = $frview.parent();
	}
	if(!$frview.hasClass('fr-view')) return;

		....
```

**Comment by stefanneculai** [comment] 2015-10-20 21:08
Duplicate of #861 .

**Closed by stefanneculai** 2015-10-20 21:08 UTC
