### ISSUE TITLE
Quote plug-in seems to need language translation.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#831] opened 2015-10-07 11:02 UTC
For example, there is a need to translate each language, as shown below.
```javascript
    // Quote ko.js
    "Quote": "\uc778\uc6a9",
    "Increase": "\uc99d\uac00",
    "Decrease": "\uac10\uc18c"

    // Quote ja.js
    "Quote": "\u5f15\u7528",
    "Increase": "\u5897\u52a0",
    "Decrease": "\u6e1b\u5c11"
```

**Comment by stefanneculai** [comment] 2015-10-07 11:04
An update will come in the following days for translations. There are more translations missing and we're working on them. Duplicate of #810 .

**Closed by stefanneculai** 2015-10-07 11:04 UTC
