### ISSUE TITLE
Deleting text has no effect if you enter no other keys

### ISSUE THREAD

**Issue by levininja** [froala/wysiwyg-editor#583] opened 2015-06-09 18:30 UTC
When you erase the contents of the editor (with backspace), and press no other keys, it does not update the hidden textarea field.  

Steps to reproduce:
1. Populate the text with javascript.  (I have this on an edit page.)
2. Select all the text in the editor
3. Hit the backspace key
4. You can see the changes have not been saved by looking at the hidden field in the console, i.e. "$('#TextAreaID').val()".  It returns the old value.

PLEASE NOTE: you can only reproduce the issue if you press NO OTHER keys while in the text editor.  If, at any time, you press some key like "k", it starts registering changes.

I have reproduced the issue in Firefox and Chrome.

**Comment by stefanneculai** [comment] 2015-06-14 12:01
I couldn't replicate it. Are you experiencing that on the master version? Also, please notice that the changes propagate to the hidden textarea based on the (typingTimer)[https://www.froala.com/wysiwyg-editor/docs/options#typingTimer] option.

**Comment by stefanneculai** [comment] 2015-07-03 13:15
We cannot reproduce this issue. Could you please provide more details?

**Comment by stefanneculai** [comment] 2015-07-10 13:08
I am closing this due to lack of communication.

**Closed by stefanneculai** 2015-07-10 13:08 UTC
Labels: cannot-reproduce
