### ISSUE TITLE
More text than selected is affected by italic/bold in Firefox, Froala 2.latest

### ISSUE THREAD

**Issue by Krisell** [froala/wysiwyg-editor#3676] opened 2019-09-24 12:31 UTC
##### Expected behavior.
Only the selected text is affected.

##### Actual behavior.
A lot more text is affected. Interestingly enough, the selected word is the only affected word in that paragraph, but the whole next paragraph is affected.

##### Steps to reproduce the problem.
 * Use Firefox, latest.
 * Use Froala 2.latest, for instance here: https://www.froala.com/wysiwyg-editor/v2.0/examples/full-featured
  * Type some text. Make a new paragraph and write some more.
  * Select a word in the first paragraph ("some" in my example)
  * Use the italic/bold-function.
  * The text below is now affected, see image.

![image](https://user-images.githubusercontent.com/25909128/65511509-a6d7b480-ded7-11e9-8553-3b56eea34f8f.png)

##### Editor version.
2.latest (issue verified on your demo site)

##### OS.
macOS and Windows

##### Browser.
Firefox (latest and ESR 52 verified).

##### Recording.
See image. If needed, I can add a recording.

**Comment by Krisell** [comment] 2019-11-08 13:19
Hi! 
This is a big issue for one of our use cases. Any updates on solving this?

**Comment by ilyaskarim** [comment] 2019-11-08 14:37
@Krisell thanks for the bug update.

**Comment by ilyaskarim** [comment] 2019-11-08 14:38
@casualuser can you mark this as bug?

**Comment by Krisell** [comment] 2019-11-26 07:50
I noticed that also the text-color feature unfortunately behaves in this way.

A really common use case is to write the text first, and fix formatting in the end, where this problem becomes a big issue.

**Comment by jeremymlane** [comment] 2019-12-10 08:01
I'm running into the same thing, but in Froala 3.

**Comment by Naartti** [comment] 2019-12-10 09:44
We have the same issue with Froala 2, and would greatly appreciate a fix.

**Comment by jeremymlane** [comment] 2019-12-13 00:12
After more digging, it seems to be caused by the fix to https://github.com/froala/wysiwyg-editor/issues/3390

**Comment by Krisell** [comment] 2020-02-07 08:41
@ilyaskarim  This seem to have been resolved in Froala 3, any chance that this fix can land in version 2 as well?

**Comment by ilyaskarim** [comment] 2020-02-18 23:58
@Krisell apologies for the late reply, The issue is fixed in 2.9.7 and no release date yet but it should be announced soon.

**Comment by fred-mevia** [comment] 2020-02-24 10:25
Yes please we need the update 2.9.7 as soon as possible ! and I don't see so much fixed issue from https://github.com/froala/wysiwyg-editor/milestone/16

**Comment by Krisell** [comment] 2020-04-07 13:40
@ilyaskarim When can we expect the 2.9.7 release?

**Comment by ilyaskarim** [comment] 2020-04-07 22:41
@Krisell I think @casualuser can answer here.

**Comment by FoxSGR** [comment] 2021-07-09 09:15
Happening in Froala 3.2.7, Firefox 89.0.2 (64-bit). Any updates?

**Comment by AnnaZot** [comment] 2021-09-09 10:17
We have a similar issue in Firefox that I can reproduce not only for inline toolbar but also here (https://froala.com/wysiwyg-editor/examples/toolbar-buttons-3/ )

Steps to reproduce: 
1. Select a part of the text or the entire text 
2. Click on bold then italics and then underline button

Actual result: 
The bold button gets disabled when clicking the other buttons. And this is just one example if we keep toggling the bold/italics/underline and also the paragraphs the behavior becomes really annoying disabling buttons that should be enabled.

**Comment by ilyaskarim** [comment] 2023-08-04 13:11
The issue is fixed in V2.9.7 and Not reproducible on latest V4.1.

**Closed by ilyaskarim** 2023-08-04 13:11 UTC
Labels: bug, version 2
