### ISSUE TITLE
inline style overflow:visible on parents is not removed when exiting fullscreen

### ISSUE THREAD

**Issue by JSteunou** [froala/wysiwyg-editor#2005] opened 2017-05-30 10:23 UTC
##### Expected behavior.

inline added style should be removed when exiting fullscreen

##### Actual behavior.

z-index is removed but not overflow visible

##### Steps to reproduce the problem.

Make a parent between body and editor with overflow:auto & overflow-x:hidden by default. It's the only parent that keep the inline overflow:hidden when exiting fullscreen

##### OS.

Windows 10

##### Browser.

Chrome Canary (and only canary, so the bug is not real until some release)

**Comment by JSteunou** [comment] 2017-05-30 10:46
I updated the previous steps, seems like overflow-x: hidden has a bigger influence

**Comment by stefanneculai** [comment] 2017-05-31 04:50
Looks like a duplicate of #2004.

**Closed by stefanneculai** 2017-05-31 04:50 UTC

**Comment by JSteunou** [comment] 2017-05-31 08:01
Seems like it, also I did not have the bug with current Chrome & Firefox. Will check again when #2004 will be closed

**Comment by JSteunou** [comment] 2017-07-19 14:46
@stefanneculai we still have the issue on 2.6.2, so it appears it was not the same as #2004. We will try to make a codepen of fiddle asap. Could you re-open this issue meanwhile?

**Comment by JSteunou** [comment] 2017-07-19 14:51
Nope sorry, false alarm, we were in 2.6.1 on one component :pray: 

Issue solved with 2.6.2 :+1:
