### ISSUE TITLE
Question: Window Resize Events Don't Play Nice

### ISSUE THREAD

**Issue by jpgilchrist** [froala/wysiwyg-editor#3126] opened 2018-10-15 17:36 UTC
##### Description
I am using the froala vue component in a very complex form. This form has many fields some of which are numbers, text fields, and some are rich text fields for which we use froala. I recently started rebuilding our hybrid application using https://quasar-framework.org (which I love) and I noticed an issue where the pages layout resize render was janky for both mobile and web clients where the height changes... for instance a keyboard opening or closing.

After debugging I found that froala internally listens to the window resize event to do several things. This is causing quasar's layout render on resize the be delayed. Furthermore, any custom `window.addEventListener('resize', () => {})` is significantly delayed, which can be problematic. 

I'd really like to find out how to make them play well together. 

##### Hack

to get around this in the meantime I listen for the `froalaEditor.initialized` event and turn off all the events with 

```javascript
export default {
  name: 'FroalaField',
  data () {
      return {
        focused: false,
        config: {
          events: {
            'froalaEditor.initialized': this.froalaEditorInitialized
          }
        }
      }
    },
  ...
  methods: {
    ...
    froalaEditorInitialized (e, editor) {
      editor.events.$off()
      if (this.disabled) {
        editor.edit.off()
      }
    }
  }
}
```

However, that makes me nervous as I don't know what the unintended consequences will be. The basic behaviors seem to work, but I'm sure a client will find something in the future... 

##### The Question

Are there any recommended ways to simply not listen to window resize events or make it play nice with other window resize event listeners?

**Comment by stefanneculai** [comment] 2018-10-23 12:08
@jpgilchrist what would be very helpful is a jsFiddle where we can reproduce it. However, it is unlikely for us to turn off the resize events because they are important incorrect positioning of the editor UI elements.

**Comment by jpgilchrist** [comment] 2018-10-23 13:30
@stefanneculai I'll try to setup something in jsfiddle. I understand you depend on the events as well, but it causes some pretty awful behavior on the rest of the application; especially on a mobile phone since the keyboard opening and closing causes these events to trigger. I'll try to show you.

**Comment by stefanneculai** [comment] 2018-12-19 16:16
@jpgilchrist do you have any updates on this? I am closing it for now, but would be happy to reopen if we'd get to a conclusion where it would make sense to implement such a feature.

**Closed** 2018-12-19 16:17 UTC
Labels: waiting-details

**Comment by jpgilchrist** [comment] 2019-06-10 16:43
@stefanneculai sorry for the massive delay, but I was reminded about this by a colleague recently. I finally got around to setting up a codepen. 

https://codepen.io/anon/pen/orvVaB?editors=1010

You can resize the window (horizontally) and see that it takes a few seconds for it to adjust the width of the quasar page. If you un-comment the line that turns off the events, then you'll notice it's significantly better. 

The end product will be a mobile application, so there aren't "page resizes" per say, but the keyboard can affect the page size, which is the main concern and causes the same issues.
