### ISSUE TITLE
I can't set font size, font family for highlight text ( selected text )

### ISSUE THREAD

**Issue by quan1997ap** [froala/wysiwyg-editor#4116] opened 2020-12-17 10:16 UTC
I can't set font size for highlight text.
The pointer alway back to start of text. 
I'm using version 3.3.5
Can u fix this soon. 
Thank dev team

**Comment by justinTNT** [comment] 2020-12-17 23:44
confirmed by comparing https://froala.com/wysiwyg-editor/examples/font-family/
to https://froala.com/wysiwyg-editor/v2-0/examples/font-family/

**Comment by dejanmartinovic** [comment] 2020-12-28 08:49
@quan1997ap the fix will be available in the next Froala release. Regards

**Comment by st-abarker** [comment] 2021-01-04 14:58
@dejanmartinovic My company's QC team was able to determine that there are issues with the following controls:

- Font Family
- Font Size
- Quote
- Align
- Paragraph Format
- Paragraph Style

Will all of these be fixed in the next release, or should we open a new issue for some of them?

**Comment by dejanmartinovic** [comment] 2021-01-05 12:22
@st-abarker The fix will be available in the next editor release (planned for tomorrow)

**Comment by erikramalho** [comment] 2021-01-06 18:40
hey @dejanmartinovic Is it solved with the v3.2.5-1 released today?

**Comment by quan1997ap** [comment] 2021-01-07 07:39
Thank for your helping. I will test and update it soon

Vào 1:40, Th 5, 7 thg 1, 2021 Erik Ramalho <notifications@github.com> đã
viết:

**Comment by st-abarker** [comment] 2021-01-07 16:24
Version 3.2.5-1 shows some significant improvements for this issue, but there are still problems with the Paragraph Format and Paragraph Style buttons. In 3.2.3 and earlier, these buttons would apply their styles to whatever paragraph the cursor was currently on. In 3.2.5-1, you now need to select the paragraph you want the styles to apply to. In addition, after applying these styles, the cursor is move to the top of the editor, which makes applying multiple styles to the same paragraph tedious.

**Comment by quan1997ap** [comment] 2021-01-08 05:42
i'm very happy when u fix this bug. It is important for my project now. Im
using it for Beta web version and still use this in future. So i hope you
can improve, and fix this bug soon.
Thanks

**Comment by ImNaveen15** [comment] 2021-01-28 10:59
@quan1997ap @dejanmartinovic Any update on this. I am facing the same problem in my project. I am using 3.2.5 version. 

Thanks in advance

**Comment by dejanmartinovic** [comment] 2021-01-28 11:02
@ImNaveen15 The problem was solved in 3.2.5-2 https://jsfiddle.net/dejan_m/scx53bqw/

**Comment by ImNaveen15** [comment] 2021-01-28 12:31
@dejanmartinovic Thanks. Was this problem solved in `react-froala-wysiwyg` too?

**Comment by dejanmartinovic** [comment] 2021-01-28 13:21
@ImNaveen15 Sure thing. You can test this demo: https://codesandbox.io/s/crimson-rain-9x5km?file=/src/index.js.

**Closed** 2023-08-04 13:13 UTC
