### ISSUE TITLE
copy image bug

### ISSUE THREAD

**Issue by wonchoe** [froala/wysiwyg-editor#2888] opened 2018-06-13 21:40 UTC
when you
![screenshot_2](https://user-images.githubusercontent.com/32915897/41379695-464c4ccc-6f28-11e8-82e4-40f3ec046b4e.png)

and then past in editor, no style="300px" here
![screenshot_3](https://user-images.githubusercontent.com/32915897/41379723-5cd7e122-6f28-11e8-972a-24242dd74de8.png)

and when you pressing 
![screenshot_4](https://user-images.githubusercontent.com/32915897/41379766-828bba24-6f28-11e8-87e7-6dda1e433472.png)
nothing happend

**Comment by stefanneculai** [comment] 2018-07-12 09:49
I am closing this as we cannot reproduce it and we haven't got additional details.

**Closed by stefanneculai** 2018-07-12 09:49 UTC
Labels: waiting-details
