### ISSUE TITLE
Firefox spell checking

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2345] opened 2017-11-14 13:16 UTC
##### Expected behavior.
Words which are spelt incorrectly should remain marked as such.

##### Actual behavior.
If a sentence contains spelling mistakes, the words are often marked as such briefly, and then cleared again. Sometimes they will be re-marked as errors. Other times that won't happen until you add a few line breaks. Generally after adding a line break, the words are now correctly marked as errors.

##### Steps to reproduce the problem.
1. Using Firefox 56, or Firefox 57, go to the demo editor on the Froala.com home page.
2. Type a string of words such as "If a word si incorectly seplt ".
3. Some of the words might stay marked as errors, though generally none of them will be.
4. Add a couple of line breaks, the three incorrectly spelt words will be marked as errors.

##### OS.
macOS or Windows

##### Browser.
Firefox 56 and 57. 

Side note: I appreciate this is something which originally seemed to see some improvement recently. One of our customers reported it as an issue with Firefox on Bugzilla and changes were made. Not sure if the update to Firefox 56 (Quantum 🙄) has caused some issues or if there have been regressions in Froala since. I also appreciate that whatever the issue is seems to be a complex one, perhaps with some issues in Firefox itself, but it does appear to be important for our users and we don't want to have to add support for the web spell check system or tell them to use other browsers.

If the issues are related to Firefox, please do report the issues to them via BugZilla if possible.

Keep up the great work :)

**Comment by stefanneculai** [comment] 2017-11-14 15:30
That seems to be introduced in FF 56 and it is happening on backspace.

**Comment by chrisdeeming** [comment] 2017-11-14 15:35
Huh, yeah it does seem to be backspace. I didn't notice it before. We're still running 2.7.0 while we wait for some of the issues @mikesul reported to be fixed in 2.7.1, but I could of course repro it on the home page editor on your site because my first step usually is to remove all the default content from that demo using backspace.

Thanks for noticing that.

**Comment by stefanneculai** [comment] 2018-01-25 12:21
@chrisdeeming do you think you could make a recording of how to reproduce this on our website?

**Comment by chrisdeeming** [comment] 2018-01-25 12:34
@stefanneculai I cannot currently reproduce the issue using Firefox 59.0b3.

Has there been any changes here on your side, or do we suspect that the regression introduced in Firefox 56 might have been fixed since?

**Comment by stefanneculai** [comment] 2018-01-25 12:35
@chrisdeeming I believe it's something from Firefox which has been fixed in the meanwhile. I am closing this. If you see it again, please send us a recording.

**Comment by chrisdeeming** [comment] 2018-01-26 11:47
@stefanneculai sorry, it can still be reproduced with a specific step - double spaces.

https://www.youtube.com/watch?v=hseA2_qLFyg

Everything seems normal until you hit double space. Then the current spelling mistake highlights disappear. Hitting enter/return will bring them back. You can then reproduce the issue with the current line by hitting double space again.

I know the Firefox spell check system isn't great, but unfortunately it more recently seems to behave correctly on other rich text editors.

**Comment by chrisdeeming** [comment] 2018-01-31 17:59
@stefanneculai @dianaprajescu just wanted to bring your attention back to this as according to the above video, the issue can still be reproduced. Hopefully will improve with future Firefox releases, but other editors do not appear to have the issue.

**Comment by chrisdeeming** [comment] 2018-03-14 11:49
We have had some reports of flakiness of the spell checking in Chrome too,

**Comment by ilyaskarim** [comment] 2022-06-25 19:38
Not reproducible on latest 4.0.12

**Closed by ilyaskarim** 2022-06-25 19:38 UTC
Labels: enhancement, firefox, backlog
