### ISSUE TITLE
Dropdowns in IE are not going away

### ISSUE THREAD

**Issue by ncmancuso** [froala/wysiwyg-editor#1694] opened 2017-01-12 19:46 UTC
##### Expected behavior.
When a font size is selected, it applies the changes and dropdown collapses

##### Actual behavior.
The fontsize dropdown does not go away (see gif)

##### Steps to reproduce the problem.
![froaladropdowns](https://cloud.githubusercontent.com/assets/6825718/21905555/d56d9842-d8d5-11e6-9623-343c1f0b50e6.gif)

##### OS.
Windows 8/10

##### Browser.
Internet Explorer (Version 11.0.9600.18500)

**Comment by kmacampbell** [comment] 2017-01-17 18:01
Hi @stefanneculai any update on this ticket? Unfortunately this bug is a blocker to us upgrading to 2.4.0, and we'd really like to upgrade soon as the release includes some other fixes we're waiting on. Thanks!

**Comment by stefanneculai** [comment] 2017-01-24 13:35
@ncmancuso @kmacampbell are you doing anything else before that because we cannot reproduce this problem?

**Comment by kmacampbell** [comment] 2017-01-24 15:54
@stefanneculai just reviewing with the team to see if we can get some additional details.

**Comment by kmacampbell** [comment] 2017-01-24 18:51
@stefanneculai looks like it may depend on IE 11 sub-version, or possibly be due to a race condition that only appears on certain machines that vary in performance / workload. Here are IE 11 versions of team members who are able to reproduce:
11.0.9600.18500, update versions 11.0.36 (Windows 8.1)
11.633.10586.0, update versions 11.0.36

And versions from team members who aren't able to reproduce:
11.0.14393.0, update versions 11.0.33 (Windows 10)
11.321.14393.0, update versions 11.0.36

**Comment by stefanneculai** [comment] 2017-03-10 22:11
We couldn't reproduce this in anyway. I am closing this until there is a consistent way of getting it reproduced.

**Closed by stefanneculai** 2017-03-10 22:11 UTC
Labels: cannot-reproduce

**Comment by shorttylad** [comment] 2017-03-24 10:07
I'm experiencing this exact issue

**Comment by stefanneculai** [comment] 2017-03-24 11:49
@shorttylad could you make a jsFiddle for this?

**Comment by shorttylad** [comment] 2017-03-31 09:39
Hi @stefanneculai 

I'm having issues strange with jsFiddle and IE so I cannot set that up for you.. Also Froala is loading fine in our product, however when I access the example on the froala web page, the toolbar is missing.

I'm trying to come up with a work around and noticed that when the font size drop down loses focus, it is hidden by putting the height to 0px. This is not happening in IE11 so the div just floats on the screen infront of the editor.

**Comment by stefanneculai** [comment] 2017-03-31 09:43
Would it be possible to make a recording?

**Comment by shorttylad** [comment] 2017-03-31 10:35
https://gyazo.com/ad7ddd57c8078d1e976fd2149cf29b1c

**Comment by shorttylad** [comment] 2017-03-31 15:38
Seems to only happen when the scrollbar is present - other divs will hide as they should.

**Comment by shorttylad** [comment] 2017-04-06 15:45
Hi @stefanneculai 
The problem has been partly resolved - when you click an option on the drop down it will disappear as expected. However, if you click away without selecting an option, the issue still occurs.

https://gyazo.com/744aebfe94b4ae4df8a6bf1e64f293a2
