### ISSUE TITLE
Pasting bullets using word cleanup loses indentation

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#2029] opened 2017-06-15 12:04 UTC
##### Expected behavior.
Copy paste from word into Froala when using MS word cleanup should still maintain indentation in lists/bullets. 

##### Actual behavior.
Indentation in lists/bullets is lost after cleaning. 

##### OS.
Mac OS

##### Browser.
Chrome

**Comment by stefanneculai** [comment] 2017-06-15 15:08
@jeremylynch could you please send a document you're pasting from?

**Comment by jeremylynch** [comment] 2017-06-18 00:09
No worries @stefanneculai 
[Sample Word document.docx](https://github.com/froala/wysiwyg-editor/files/1082837/Sample.Word.document.docx)

**Comment by stefanneculai** [comment] 2017-06-22 17:14
Duplicate of #1967.

**Closed by stefanneculai** 2017-06-22 17:14 UTC
Labels: waiting-details
