### ISSUE TITLE
can not use inlinetoolbar ' toolbarVisibleWithoutSelection: false' option in korean, chinese 

### ISSUE THREAD

**Issue by Wuyialex** [froala/wysiwyg-editor#2021] opened 2017-06-06 12:55 UTC
I am trying to note appliacation using Froala.
when I start typing Korean in inline mode, the inline toolbar is not visible from that moment.
But If I use 'toolbarVisibleWithoutSelection: true', this problem doesn't appear.
There are same problem in chinese.

Probably it seems that you have made the display of the inline toolbar change from none to block when user select the letters.

However, when i start to speak Korean or Chinese, display: none does not change to display block.
If i delete typed Korean and Chinese, the toolbar work normally again.
There are same situation in Froala Website Example(https://codepen.io/Froala/pen/evobdr)

**Comment by stefanneculai** [comment] 2017-06-15 15:20
@Wuyialex when using `toolbarVisibleWithoutSelection: false`, the inline toolbar should not appear when you type or end typing.

**Comment by largeden** [comment] 2017-06-16 15:29
@Wuyialex hello :p
I am interested in this issue.
But I failed to reproduce the problem.
What OS and browser issue are you having?
For reference, how about dragging with the mouse?

**Comment by Wuyialex** [comment] 2017-06-18 08:01
Mac OSX sierra, chrome, safari.....
After typing asia languages, toolbar doesn't appear in drragging with mouse.
But I found that it does in selection with keyboard(shift + cursorkey).
There are same situation in (https://codepen.io/Froala/pen/evobdr)
This is my config in Froala.
const config = {
	spellcheck: false,
	placeholderText: 'Rian',
	editorClass: 'mainEditor',
	width: '100%',
	charCounterCount: false,
	tabSpaces: 8,
	toolbarInline: true,
	toolbarVisibleWithoutSelection: false,
	colorsDefaultTab: 'background',
	colorsBackground: ['#FFFAA5', '#9BDBFF', '#FF3466', 'REMOVE'],
	colorsText: ['#FFFAA5', '#9BDBFF', '#FF3466', 'REMOVE'],
	toolbarButtonsMD: [
		'bold',
		'color',
		'italic',
		'underline',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
		'html',
	],
	toolbarButtonsSM: [
		'bold',
		'color',
		'italic',
		'underline',
		'strikeThrough',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
		'html',
	],
	toolbarButtonsXS: [
		'bold',
		'color',
		'italic',
		'underline',
		'strikeThrough',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
		'html',
	],
	toolbarButtons: [
		'bold',
		'color',
		'italic',
		'underline',
		'strikeThrough',
		'paragraphFormat',
		'align',
		'formatOL',
		'formatUL',
		'outdent',
		'indent',
		'insertLink',
		'insertHR',
		'print',
		'insertTable',
		'html',
	],
	paragraphFormat: {
		N: 'Normal',
		H4: 'Code',
		H3: 'Head 3',
		H2: 'Head 2',
		H1: 'Head 1',
	},
};

**Comment by largeden** [comment] 2017-06-18 09:52
@Wuyialex 
Thank you for a detailed explanation.

@stefanneculai 
I found this problem to appear in the chrome safari. (It does not appear in Firefox.)

##### chrome
![inline_1](https://user-images.githubusercontent.com/5575931/27259827-e6e4a8b6-5456-11e7-954f-a88c7bf3de5a.gif)

##### safari
![inline_2](https://user-images.githubusercontent.com/5575931/27259830-f3dac5e6-5456-11e7-84d5-5f171aac9800.gif)

##### firefox (The toolbar work.)
![inline_3](https://user-images.githubusercontent.com/5575931/27259831-fd95bd34-5456-11e7-8273-49df2c8916a5.gif)


---

### Reproduce

##### Step1.
https://codepen.io/Froala/pen/evobdr access.

##### Step2.
toolbarVisibleWithoutSelection: false

##### Step3.
Clear all text.

##### Step4.
Typing '한글'

###### Step4-1.
Please add Korean language.
![screen shot 2017-06-18 at 18 40 11](https://user-images.githubusercontent.com/5575931/27259782-c6aed450-5455-11e7-9507-ed5a9423481f.png)

###### Step4-2.
Change the key input to '2-set Korean' and input it.

```
한글
ㅎ + ㅏ + ㄴ + ㄱ + ㅡ + ㄹ
g + k + s + r + m + f
```

##### Step5.
Drag
(The toolbar does not work.)

##### Step6.
Enter a dot (.) Or any regular key.
(The toolbar work.)

---

It seems to be a problem when only IME key is put on.

**Comment by largeden** [comment] 2017-06-19 08:31
@stefanneculai 
I found the cause for this issue.
We define not to display the inline toolbar when the last typing is IME true.
If editor.keys.isIME () is removed, there is no problem in operation.
How about removing it?

```javascript
// froala_editor.js
    function showInline (e, force) {
      setTimeout(function () {
        if ((!e || e.which != $.FE.KEYCODE.ESC) && editor.selection.inEditor() && editor.core.hasFocus() && !editor.popups.areVisible()) {
          if (editor.opts.toolbarVisibleWithoutSelection || (!editor.selection.isCollapsed() && !editor.keys.isIME()) || force) { //<- here !editor.keys.isIME()
            editor.$tb.data('instance', editor);
```

**Comment by stefanneculai** [comment] 2017-07-19 15:22
@largeden thanks for helping us to nail this down. All should be fixed now.

**Closed** 2017-07-19 15:22 UTC
Labels: bug
