### ISSUE TITLE
Incorrect background color

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1720] opened 2017-01-29 00:22 UTC
##### Steps to reproduce the problem.

1. Type something like: TEXT
2. Apply font size: 30
2. Apply background

##### OS.
macOS 

##### Browser.
macOS, Chrome 55.0.2883.95 (64-bit)

![img-2017-01-29-03-18-57](https://cloud.githubusercontent.com/assets/803674/22400867/bea0de22-e5d1-11e6-90cd-623a62357f54.png)

**Comment by stefanneculai** [comment] 2017-01-30 10:50
Duplicate of #1715

**Closed by stefanneculai** 2017-01-30 10:50 UTC
