### ISSUE TITLE
Video will not load via URL or Embed HTML

### ISSUE THREAD

**Issue by bpautsch** [froala/wysiwyg-editor#3666] opened 2019-09-13 15:00 UTC
Video Source: https://3stepsolutions.s3.amazonaws.com/assets/custom/001061/videos/roots-w-megs.mp4

HTML: 
&lt;video width="320" height="240" controls&gt;
    &lt;source src="https://3stepsolutions.s3.amazonaws.com/assets/custom/001061/videos/roots-w-megs.mp4" type="video/mp4"&gt;
&lt;/video&gt;

### Expected behavior.
Scenario 1: Click Insert Video, click "By URL", paste in URL and click "Insert". Video should show.
Scenario 2: Click Insert Video, click "Embedded Code", paste in HTML and click "Insert". Video should show.

### Actual behavior.
In both scenarios, receive error message "Something went wrong. Please try again.".

Comments:
1. The video is large (801 MB), but we have: "videoMaxSize: 1048576000‬"
That's 1000 MB or 1 GB (1024 x 1024 x 1000).
2. There are no errors in the Console.
3. If I open the Froala source editor, paste in the HTML, and switch back to view mode, it render the video and plays perfectly.

### Editor version.
Froala v2.9.6

### OS.
Windows 10

### Browser.
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by deevannaveed** [comment] 2020-02-28 05:02
Any Updates on this error?

**Comment by DevS1993** [comment] 2020-03-05 12:11
1. The "By URL" option works url's from video players e.g. Youtube, Vimeo. Doesn't work with direct public links to videos. The editor inserts an iFrame with the URL input by the user.

2. The "Embedded Code" option works with <embed> and not with <video> . I am not sure why it works like this.

**Comment by laxman-spidey** [comment] 2021-09-29 06:10
@bpautsch I'm also in need of the similar functionality. Did you find any solution or alternate for it.

**Comment by bpautsch** [comment] 2021-09-29 12:56
> @bpautsch I'm also in need of the similar functionality. Did you find any solution or alternate for it.

I have not. It seems like it would be an easy fix.

**Comment by smshuja** [comment] 2021-11-23 07:36
This is an important feature. Would be great if it can be added.

**Comment by ilyaskarim** [comment] 2022-06-30 22:59
The issue is already being fixed in V3.1.0: https://froala.com/wysiwyg-editor/changelog/#3.1.0

**Closed by ilyaskarim** 2022-06-30 22:59 UTC
Labels: bug, version 2
