### ISSUE TITLE
Unable to add video embed code with space between iframe tag

### ISSUE THREAD

**Issue by joeholdcroft** [froala/wysiwyg-editor#3201] opened 2018-12-07 11:50 UTC
##### Expected behavior.

Should be able to add iFrame video both with and without spaces (or any characters really) between the opening and closing `iframe` tags.

##### Actual behavior.

The video is not added when the embed code contains a space between the opening and closing `iframe` tags.

##### Steps to reproduce the problem.

Paste the following video embed code into Video Embed input in the [Full Featured demo](https://www.froala.com/wysiwyg-editor/examples/full-featured):

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/ferZnZ0_rSM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen> </iframe>
```

It won't add the video. Now remove the space between the tags, and it adds the video no problem:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/ferZnZ0_rSM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

##### OS.

Mac OS X 10.13.6

##### Browser.

Chrome 70.0.3538.110

**Comment by stefanneculai** [comment] 2018-12-07 13:40
See https://github.com/froala/wysiwyg-editor/issues/3152#issuecomment-437371627.

**Comment by joeholdcroft** [comment] 2018-12-07 15:19
Fair enough @stefanneculai, thanks. 

Would you consider changing the default? Some video providers will have some characters between the opening/closing `iframe` tag. This issue was brought to our attention by a user trying to embed from livestream.com, where they provide the embed code with a space between the opening/closing `iframe` tag.

**Comment by stefanneculai** [comment] 2018-12-13 11:50
Reopening it and marking as an `enhancement`.

**Comment by stefanneculai** [comment] 2018-12-17 11:38
Duplicate of https://github.com/froala/wysiwyg-editor/issues/3081

**Closed by stefanneculai** 2018-12-17 11:38 UTC
Labels: enhancement
