### ISSUE TITLE
Pasting links into Froala within Bootstrap Modal scrolls page to top.

### ISSUE THREAD

**Issue by timavaza** [froala/wysiwyg-editor#3265] opened 2019-01-31 16:14 UTC
##### Expected behavior.
Links should paste as normal into Froala, without affect the page scroll position

##### Actual behavior.
Page instantly scrolls to top.. leaving the Froala editor and your current cursor position off the screen

##### Steps to reproduce the problem.
Use standard Bootstrap 3 modal dialog, with Froala inside dialog. Have long enough content that the modal scrolls.

##### Browser.
Chrome, Firefox

##### Recording.
JSFiddle: just scroll the modal dialog down, and then paste any link into the editor.
https://jsfiddle.net/wc5c3jhk/1432/

**Comment by stefanneculai** [comment] 2019-02-05 14:48
@timavaza this should be fixed on the current 2.9.2 version. Do you think you could check again and let us know if you still face the problem?

**Comment by behram-khan** [comment] 2019-02-19 10:23
@stefanneculai It seems this issue is broken again in version 2.9.3. Here is the JSFiddle link https://jsfiddle.net/wc5c3jhk/1432/

Can you please get this addressed as we have thousands of customers using this particular feature?

**Comment by timavaza** [comment] 2019-02-20 10:05
+1.
This is broken again in 2.9.3.

**Comment by behram-khan** [comment] 2019-02-20 14:56
@stefanneculai Quick update. The bug still exists in version 2.9.2 for Safari browser on Mac OS as well.

So in summary the bug is back on all browsers in version 2.9.3 and still exists for Safari browser in version 2.9.2

Let me know if you need any further details.

**Comment by stefanneculai** [comment] 2019-02-21 10:59
I can confirm that it is a regression - we'll address this shortly.

**Comment by navneetnagpal** [comment] 2019-02-22 10:26
This issue is coming because modal dialog using transform property which changes the behavior of `position:fixed` to work like `absolute in relative`.  There is already reported bug to this behavior 
https://bugs.chromium.org/p/chromium/issues/detail?id=20574&desc=2
and it looks like they aren't going to fix that.

Here is temporary workaround to fix this :https://jsfiddle.net/w9kv27up/3/

Thanks,
navneet

**Closed** 2019-02-22 10:36 UTC
Labels: bug
