### ISSUE TITLE
I have same problem

### ISSUE THREAD

**Issue by riv-riv** [froala/wysiwyg-editor#4224] opened 2021-05-03 10:25 UTC
##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### Editor version.
If you don't know it, please see https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717049-How-can-I-find-my-editor-version-.

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by ilyaskarim** [comment] 2022-02-07 14:50
Hi @riv-riv , Can you please provide us with more details (recording, steps to reproduce, demo) about the issue you are having? If the issue is already being resolved/fixed, You can close the issue.

**Closed** 2022-06-29 19:31 UTC
