### ISSUE TITLE
Missing translation (pt_br)

### ISSUE THREAD

**Issue by giovanigenerali** [froala/wysiwyg-editor#2884] opened 2018-06-12 21:13 UTC
##### Expected behavior.
Missing translation to the button 'save' in pt_br;

##### Actual behavior.
![screen shot 2018-06-12 at 18 08 24](https://user-images.githubusercontent.com/41435/41317459-a7e808d0-6e6b-11e8-9df0-83fe527712e5.png)

##### Steps to reproduce the problem.
Create a ```key:value``` here https://github.com/froala/wysiwyg-editor/blob/master/js/languages/pt_br.js
```
'Save': 'Salvar'
```

##### OS.
![screen shot 2018-06-12 at 18 13 09](https://user-images.githubusercontent.com/41435/41317658-49c6de92-6e6c-11e8-93d3-2a10c80bfe9a.png)

##### Browser.
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
```

**Comment by stefanneculai** [comment] 2018-10-01 13:21
Duplicate of #2763.

**Closed by stefanneculai** 2018-10-01 13:21 UTC
Labels: enhancement
