### ISSUE TITLE
After copypaste cursor position is before copied content

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#585] opened 2015-06-15 12:07 UTC
Hello. After copypaste (as ms word, notepad etc do) cursor must be in the last position of copied content.

**Comment by kotmatpockuh** [comment] 2015-06-24 11:39
Hi. Is it real, that you fix this bug till 28/06 ?

**Comment by stefanneculai** [comment] 2015-06-24 11:41
The issue is mainly fixed, but there are still some edge scenarios when the issue occurs. In version 2 that we'll release next week most probably the issue will be fixed completely.

**Comment by kotmatpockuh** [comment] 2015-07-01 08:58
hello, any news?
i have this bug, and need to solve it till friday, сan I rely on you?

**Comment by stefanneculai** [comment] 2015-07-01 09:03
I understand that you are rushing, but please stop spamming us. We'll not fix issues faster if you keep spamming us. As I said it will be fixed in the version 2.0. Today we're starting to write the documentation for it (https://twitter.com/froala_labs/status/615468201313456128). Once we finish the documentation we'll release it. Taking into consideration that we have to rewrite the entire documentation it won't be ready before Friday for sure.

**Comment by ronnyvonni** [comment] 2015-07-08 14:02
same bug
for 23 you can not fix this bug
what the f**k ?
for what i must pay?

**Comment by stefanneculai** [comment] 2015-07-10 12:17
It's fixed on the master.

**Closed by stefanneculai** 2015-07-10 12:17 UTC
Labels: bug
