### ISSUE TITLE
Copying text from Froala

### ISSUE THREAD

**Issue by kaniansky** [froala/wysiwyg-editor#2394] opened 2017-12-04 13:34 UTC
##### Expected behavior.
The whole text is pasted in one line

##### Actual behavior.
Multiple lines should be kept.

##### Steps to reproduce the problem.
* Write a text with multiple lines in Froala editor
* Copy or cut the text
* Paste it to a multiline editor

##### OS and Browser
Win10 x64 Chrome 62

**Comment by stefanneculai** [comment] 2017-12-04 19:12
@kaniansky could you please make a recording? We couldn't reproduce it.

**Comment by kaniansky** [comment] 2018-01-08 11:48
it seems to be fixed... either by using the newest version of an editor or maybe by doing some changes on our side... text is copied with new lines

but spaces (tabs also) at the beginnings of each line are not kept when copying multiple lines to Froala editor (v. 2.7.3) from elsewhere.

**Comment by stefanneculai** [comment] 2018-01-08 17:40
@kaniansky would it be possible to send us a link from the page where you're pasting from?

**Comment by kaniansky** [comment] 2018-01-09 11:12
I am pasting from NetBeans IDE 8.2 but it happens with every text where line starts with a whitespace, it gets trimmed, you can try copying this text to froala:
```
	tab
        spaces
```

**Comment by dianaprajescu** [comment] 2018-01-11 15:52
Closing this in favor of #2333

**Closed by dianaprajescu** 2018-01-11 15:52 UTC
Labels: waiting-details
