### ISSUE TITLE
Editor scrolls up on pressing enter when using two editor instances

### ISSUE THREAD

**Issue by KenticoPavelV** [froala/wysiwyg-editor#4163] opened 2021-02-04 11:47 UTC
##### Expected behavior.
Enter a new line or paragraph and do not scroll when not needed

##### Actual behavior.
When having two editor instances with longer content, pressing enter in second one scrolls up onto first editor instance.
Discovered when testing fixed BUG #4096

##### Steps to reproduce the problem.
Add two instances of Froala editor on a page
Enter any longer content in both of them (several paragraphs of a lorem ipsum)
Place cursor anywhere in the second editor instance and press enter

You can also use pre [prepared jsFiddle](https://jsfiddle.net/un5x81m3/)

##### Editor version.
3.2.6

##### OS.
Windows 10 (Ver. 1909, build 18363.1316)

##### Browser.
Google Chrome Version 88.0.4324.146 (Official Build) (64-bit)

##### Recording.
![scrollingAway](https://user-images.githubusercontent.com/15729915/106888099-5a64d180-66e6-11eb-8515-ad7cadab3b87.gif)

**Comment by thabrlawrenz** [comment] 2021-02-05 04:55
We have the same issue. For me even when there is just one editor, once I have 10 lines (pressing enter 10 times). Then pressing enter for the 11th line will scroll to top.

**Comment by IchigoWalker** [comment] 2021-02-24 17:04
I have exact "scrolling to the first instance" behaviour when clicking Save button after editing NOT first instance. Text blocks is short btw. Looks like the issue is wider and related with multiple editors on the same page.

**Comment by ke-an** [comment] 2021-04-26 21:43
Same issue with one editor, Froala version 3.2.6-1. Enter pressed in the table cell scrolls the page to top.

**Comment by MahmudurKhan** [comment] 2021-06-15 01:55
I have faced the same issue with version 3.2.6-1 even with one editor. Pressing enter triggers a scroll to top action on the page.

**Comment by sherbsherb** [comment] 2021-07-28 17:43
v4.0.3 still has this bug

**Comment by nirvparekh** [comment] 2021-08-06 12:48
Yes, I'm facing the same

**Comment by petrinecp** [comment] 2021-11-11 09:46
Seems to be fixed in 4.0.4+
https://jsfiddle.net/mnLbg5p4/

**Comment by MeghashreeAP** [comment] 2022-01-13 06:43
Thank you for your feedback.
This issue is not reproducible on latest branch.

**Comment by ilyaskarim** [comment] 2022-06-26 21:22
Fixed in V4.0.4 https://froala.com/wysiwyg-editor/changelog/#4.0.4.

**Closed by ilyaskarim** 2022-06-26 21:22 UTC
