### ISSUE TITLE
2.7.2 : cutting text broken on macOS

### ISSUE THREAD

**Issue by YannLeBihan** [froala/wysiwyg-editor#2390] opened 2017-12-03 09:47 UTC
##### Expected behavior :

Trying to cut some text from a Froala editor

##### Actual behavior :

Whatever the used method (`cmd-x` keyboard shortcut, `Edit -> Cut` menu or contextual menu) cutting text has stopped working since version 2.7.2

##### Steps to reproduce the problem :

Just go to [Froala's site](https://www.froala.com/wysiwyg-editor) and try to cut some content from the demo editor

##### OS :

macOS 10.13.1

##### Browsers :

Safari and Chrome, both at highest versions

**Comment by kaniansky** [comment] 2017-12-04 13:19
User is able to select all text and cut it but not a substring

**Comment by stefanneculai** [comment] 2017-12-04 13:20
Duplicate of #2382.

**Closed by stefanneculai** 2017-12-04 13:20 UTC
