### ISSUE TITLE
Pasting a numbered list from Word converts to bulleted list

### ISSUE THREAD

**Issue by eddcvjm** [froala/wysiwyg-editor#651] opened 2015-08-20 08:34 UTC
Hi,
The following scenario was tested on the froala site: https://www.froala.com/wysiwyg-editor/docs/examples

Steps to reproduce:
 - Create a numbered list on a word document, like the following one:
        1. Numbered1
        2. Numbered2
        3. Numbered3

 - Copy the numbered list from the word document
 - Paste it on the froala editor

Expected result:
 - The same numbered list

Actual result:
 - The numbered list is converted to a bulleted list

We are changing from TinyMCE to Froala editor and we had the expected result on TinyMCE.

Thanks

**Comment by stefanneculai** [comment] 2015-08-20 21:04
Duplicate of #612.

**Closed by stefanneculai** 2015-08-20 21:04 UTC

**Comment by eddcvjm** [comment] 2015-08-25 10:41
Hi,
Just an update on this.
The issue happens on Chrome, but not on IE11

Thanks

**Comment by stefanneculai** [comment] 2015-08-25 10:51
We know that. To keep the OL when pasting from Word in other browsers than IE requires a lot of additional code and we might create a plugin for that in the future. However, we cannot commit to that right now.
