### ISSUE TITLE
Clear formatting doesn't remove styles

### ISSUE THREAD

**Issue by markedmondson** [froala/wysiwyg-editor#1830] opened 2017-03-11 00:19 UTC
##### Expected behavior.
The clear formatting button should revert text back to no styles.

##### Actual behavior.
It seemingly does nothing.

##### Steps to reproduce the problem.
Add text, apply styles (or paste with styles), highlight text, click "clear formatting" button.

![clear-formatting](https://cloud.githubusercontent.com/assets/1653699/23818140/547ce06c-05ad-11e7-80a7-878463882ca8.gif)

##### OS.
OSX Sierra

##### Browser.
Chrome 56

**Comment by stefanneculai** [comment] 2017-03-12 12:41
Duplicate of #1827 .

**Closed by stefanneculai** 2017-03-12 12:41 UTC

**Comment by starceaker** [comment] 2017-05-12 14:09
It indeed looks like a duplicate, however your duplicate got closed without an answer / solution as far as I can tell.

Did anyone provide an answer for this one? It doesn't seem to clear styles (bold and italic are cleared for example but fr-text-gray class not).

**Comment by stefanneculai** [comment] 2017-05-13 13:33
@starceaker that has been closed as part of a commit we made in the editor. Should be fixed in version 2.6.0.
