### ISSUE TITLE
Firefox spell check behavior

### ISSUE THREAD

**Issue by irphilli** [froala/wysiwyg-editor#1814] opened 2017-03-09 00:26 UTC
##### Expected behavior.
Spell check highlights misspelled words as you type.

##### Actual behavior.
Misspellings seem to only show on the last changed word on a line, until you press enter.  I'm not sure if this is a bug with FireFox itself or not, but it only seems to happen with a Froala editor (a normal contenteditable div is OK)

##### Steps to reproduce the problem.
Screengrab:
![spellcheck](https://cloud.githubusercontent.com/assets/345511/23730354/d24f7362-041b-11e7-87e3-4a369b7adb5a.gif)

##### OS.
macOS Sierra

##### Browser.
FireFox Latest (52)

**Comment by stefanneculai** [comment] 2017-03-09 19:01
Duplicate of #1432. We are in the process of integrating a 3rd party spellchecker and should be available pretty soon.

**Closed by stefanneculai** 2017-03-09 19:01 UTC
