### ISSUE TITLE
cordova ios: backspace add weird characters

### ISSUE THREAD

**Issue by greggreenhaw** [froala/wysiwyg-editor#3117] opened 2018-10-10 14:36 UTC
cordova ios: 
backspace adds this character instead of deleteing: €‹

**Comment by greggreenhaw** [comment] 2018-10-10 16:38
Found the issue

If the following hack is removed from the _backspace method it works fine.
 if (editor.helpers.isIOS()) {
          var range = editor.selection.ranges(0);
          range.deleteContents();
          range.insertNode(document.createTextNode('\u200B'));
          var sel = editor.selection.get();
          sel.modify('move', 'forward', 'character');
        }



 function _backspace(e) {
      // There is no selection.
      if (editor.selection.isCollapsed()) {
        editor.cursor.backspace();

        if (editor.helpers.isIOS()) {
          var range = editor.selection.ranges(0);
          range.deleteContents();
          range.insertNode(document.createTextNode('\u200B'));

          var sel = editor.selection.get();
          sel.modify('move', 'forward', 'character');
        }
        else {
          e.preventDefault();
          e.stopPropagation();
        }
      }

      // We have text selected.
      else {
        e.preventDefault();
        e.stopPropagation();

        editor.selection.remove();
      }

      editor.placeholder.refresh();
    }

**Comment by stefanneculai** [comment] 2019-02-05 16:22
Unfortunately, we require this in order to have the editing work correctly. Do you think you could create an app where to replicate this?

**Comment by stefanneculai** [comment] 2019-02-27 10:59
I am closing this for now as we don't have a way to reproduce it and because the usage of the editor in Cordova apps is quite isolated.

**Closed by stefanneculai** 2019-02-27 10:59 UTC
Labels: waiting-details
