### ISSUE TITLE
null is not an object (evaluating 'b.html')

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#1436] opened 2016-08-03 07:08 UTC
When calling `destroy()` on a Froala Element, we are intermittently seeing:

Error: null is not an object (evaluating 'b.html')
v
v
destroy

##### Steps to reproduce the problem.
So far I have been unable to reproduce the exact steps to cause this. I have done some debugging and Froala does seem to be initialised on the element. (also checked that jQuery is actually retrieving the correct element)

##### OS.
OS X 10.11

##### Browser.
Safari 9.1.2

**Comment by stefanneculai** [comment] 2016-08-03 07:32
Could you please send us a link where we can reproduce it?

**Comment by theknet** [comment] 2016-08-03 08:09
I'm afraid this is an internal project and I cannot provide a link. I will run some more tests today and see if I can find a particular scenario where this happens.

**Comment by stefanneculai** [comment] 2016-08-23 09:42
I am closing this because we cannot reproduce it. If you could provide the details to reproduce it, we would be happy to look over it.

**Closed by stefanneculai** 2016-08-23 09:42 UTC
Labels: cannot-reproduce

**Comment by Panman8201** [comment] 2016-10-14 18:52
Humm... I'm getting something similar but don't know when (the error is showing up in our Sentry.io database).

> TypeError apps/reciprocity/assets/vendor in f
> null is not an object (evaluating 'b.$tb.find')

Within the minified froala editor 2.3.4 file, it's on line 11 column 23341. Specifically within this function:

```js
f() {
    var a = e();
    b.$tb.find(".fr-separator").remove(), b.$tb.find("> .fr-command").addClass("fr-hidden");
    for (var c = 0; c < a.length; c++)
        if ("|" == a[c] || "-" == a[c]) b.$tb.append(b.button.buildList([a[c]]));
        else {
            var d = b.$tb.find('> .fr-command[data-cmd="' + a[c] + '"]'),
                f = null;
            d.next().hasClass("fr-dropdown-menu") && (f = d.next()), d.removeClass("fr-hidden").appendTo(b.$tb), f && f.appendTo(b.$tb)
        }
}
```

**Comment by mattjhoughton** [comment] 2017-10-16 09:27
I've found out how to reproduce this on our end - if I have 2 editors on a page and add/edit/delete a link on each and then destroy each of the editors with `element.froalaEditor('destroy');` then it will throw the error. Making sure `element` is defiantly the correct ones, does not fix it.

Has anyone found a way around this?

**Comment by stefanneculai** [comment] 2017-10-16 13:27
@mattjhoughton are you able to reproduce this on the latest version 2.7.0? Could you make a jsFiddle? Thanks.
