### ISSUE TITLE
Toolbar selection box On mouseover, the scroll jumps to the top. 

### ISSUE THREAD

**Issue by Dofff** [froala/wysiwyg-editor#2971] opened 2018-07-17 23:38 UTC
Expected behavior.
Hovering over the selection box should have no effect.

Actual behavior.
If you hover your mouse over the selection box,
you will jump to the top of the editor.

Steps to reproduce the problem.
1. Scroll to the bottom of the editor.
2. hover after toolbar button click.
3. scroll jump to the top.
![image](https://user-images.githubusercontent.com/26613612/42851091-c2c53f0e-8a65-11e8-9710-0852dea6d20a.png)

OS.
Windows 7

Browser.
IE 11

**Comment by stefanneculai** [comment] 2018-07-20 13:13
Duplicate of #2719

**Closed by stefanneculai** 2018-07-20 13:13 UTC
