### ISSUE TITLE
MARKER TypeError: Cannot read property 'nextSibling' of undefined(…)

### ISSUE THREAD

**Issue by voidale** [froala/wysiwyg-editor#836] opened 2015-10-08 04:03 UTC
Hi, I'm using the latest 2.0.0-rc3 version, And I'm getting this error when I initialize froala editor manually on `dblclick` event. 

It's at line 2715 function "Insert a single marker." also not sure if this related but my div looks like a sticky note when I double click sometimes "Type something" appears one line below the first one, it inserts a visible empty line I would like to avoid it and add no new lines if possible. 

Thank you.

**Comment by euangoddard** [comment] 2015-10-08 11:03
I get this issue too, but when ever the editor is empty and it receives focus or a click I see the message in the console.

**Comment by stefanneculai** [comment] 2015-10-08 11:11
Could you make a jsFiddle for it? I couldn't replicate at my end. 

Could also let us know the OS and browser you're using?

**Comment by euangoddard** [comment] 2015-10-08 11:24
OK. Will do

**Comment by euangoddard** [comment] 2015-10-08 11:34
I have created a Fiddle with code to as close as that I'm using and I don't get the message. I suspect it's something subtle and it's a log message not an error so it's not an issue for me.

**Comment by stefanneculai** [comment] 2015-10-08 11:42
@euangoddard Yes, there is `try {} catch () {}` code block and it shouldn't break features. 

@voidale if you could make a jsFiddle for it we can definitely look over.

**Comment by voidale** [comment] 2015-10-08 12:22
@stefanneculai here is it https://jsfiddle.net/o67m3L6e/2/embedded/result/ but if it's either working because it's jsfiddle or because its unlicensed one, But it's a bug on `inline` mode the marker adds a new line,  If it's possible I can email you a link where it will be available on my website for testing, I don't do anything unusual so I think. It's also happens 1 after every new init of froala.

**Comment by voidale** [comment] 2015-10-08 12:27
![bug](https://cloud.githubusercontent.com/assets/4450730/10366142/a2494296-6dc8-11e5-8146-cdbab885bbcd.gif)

**Comment by rjsmith** [comment] 2015-10-08 20:51
I have a repo jsFiddle for this:

https://jsfiddle.net/094spee6/10/embedded/result/

The trick I found was two have two FE instances. Simply clicking into one then the other then back again triggers the MARKER TypeError.

On Chrome 45 iOS

**Comment by euangoddard** [comment] 2015-10-09 08:03
I can confirm this happens in Chrome 45 on Linux. This must have been the root cause of the issue I experienced since my application can have multiple editors on the same page.

It doesn't happen in Firefox 41

**Comment by voidale** [comment] 2015-10-09 09:24
Hey thanks everyone for more information It's win10 chrome over here, It's clearly a bug, Which in my case introduce a blank new line that I really don't need @stefanneculai any update on this?

**Comment by stefanneculai** [comment] 2015-10-09 17:45
@voidale @euangoddard @rjsmith could you please check the last commit and let me know if that fixes it?

**Comment by rjsmith** [comment] 2015-10-10 15:26
Hi @stefanneculai yes, that does seem to have fixed the problem.

**Comment by voidale** [comment] 2015-10-12 05:53
@stefanneculai I don't get the error anymore but new line is still added anyway to disable it? 
`<span class="fr-marker" style="display: inline; line-height: 0;">&#8203;</span>`

**Comment by euangoddard** [comment] 2015-10-13 14:42
@stefanneculai yes this has fixed the issue for me too

**Comment by stefanneculai** [comment] 2015-10-14 17:12
@voidale would it be possible to send me a link to a page where that is happening. If you don't want to make it public then please use the email address from my profile.

**Comment by stefanneculai** [comment] 2015-10-16 16:30
@voidale could you send me a link to a page where that is happening using the email address from my profile? Thank you.

**Comment by adamgins** [comment] 2015-10-20 23:22
@stefanneculai thanks for the recent updates V2 looks great. 

Sorry I am a bit confused, was this issue fixed in the main package, but it has not made it into the Meteor package? I have been using RC3 via https://github.com/froala/meteor-froala and meteor-reactive... it seemed like it was fixed, so I was not sure if perhaps it was not rolled into that release so it could be picked up by https://github.com/froala/froala-reactive ? or perhaps the problem sill exists?

**Comment by adamgins** [comment] 2015-10-22 11:10
@stefanneculai @rjsmith thanks for you responses... I have setup a debug Buzzy site here http://debug.buzzy.buzz:
1) you'll need to ignore SSL warnings - no SSL on the debug site
2) create an account with email/password or use Gmail to login (FB, Microsoft won't work)
3) Go through sign up process
4) You'll eventually land at a blank home page 
5) Click the (+) "New Buzz" top right and select `New Conversation` 
![image](https://cloud.githubusercontent.com/assets/7233741/10663663/e2a68380-7908-11e5-8626-483cbee604ca.png)
- then select "Create Now" 
![image](https://cloud.githubusercontent.com/assets/7233741/10663674/edffc39a-7908-11e5-957e-eeea6aaaf712.png)
 (you don't need to invite anyone) - this will create a new conversation buzz
6) Click the "+ Add Content" 
![image](https://cloud.githubusercontent.com/assets/7233741/10663679/f7888aaa-7908-11e5-985a-af14bf99de1d.png)
 button and add a "Text" 
![image](https://cloud.githubusercontent.com/assets/7233741/10663685/0147a1d4-7909-11e5-9173-6c4cd00cfff1.png)
component, which is a Froala v2 item
7) When you click into that 
![image](https://cloud.githubusercontent.com/assets/7233741/10663693/0ce14f36-7909-11e5-8af1-6bda935ab349.png)
you'll see the Froala Editor:
![image](https://cloud.githubusercontent.com/assets/7233741/10663703/1f8ceae6-7909-11e5-889f-f1da8611d907.png)

If you click into the editor, you should see the error in the console - eg `MARKER TypeError: Cannot read property 'nextSibling' of undefined(…)`

Any help appreciated.

**Comment by stefanneculai** [comment] 2015-10-22 11:14
The problem has been fixed on master, but the fix hasn't got yet in meteor, angular, rails or other framework plugins.

**Comment by adamgins** [comment] 2015-10-26 02:03
@stefanneculai thanks. Any eta on this pls, so I can plan around it? Really hoping to get v2 as it sorts a number of issues for  us and looks like some awesome improvements.

**Comment by stefanneculai** [comment] 2015-10-26 12:05
@adamgins This week.

**Closed by stefanneculai** 2015-10-26 12:05 UTC
Labels: cannot-reproduce

**Comment by adamgins** [comment] 2015-10-30 19:31
Hi any update pls? Keen to move to v2 on meteor

**Comment by stefanneculai** [comment] 2015-10-30 21:18
We're doing final touches on V2. Today we've fixed all the issues marked as `bug` and there are only few more things to do.

**Comment by adamgins** [comment] 2015-10-30 21:30
Awesome! Thanks heaps .. looking forward to it.
