### ISSUE TITLE
Feature Request : Put linkAutoPrefix into URL Field

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1299] opened 2016-05-25 19:19 UTC
It makes more sense to pre-populate the URL field with the linkAutoPrefix in the link popup rather than prepending linkAutoPrefix after the user presses Insert. That way if the user decides they don't want a prefix they can simply delete it and put in the URL of choice. The current way isn't obvious that the link has been prepending without checking the link URL again.

**Comment by stefanneculai** [comment] 2016-05-26 09:19
`linkAutoPrefix` option was designed to add a prefix to all inserted links in the editor. There are cases when someone would want to set the prefix to `/foo` and have this prefix for all the links inserted. Anyway, this option could be improved a little and we have it on our TODO list. Thanks for the suggestion - I am closing this here because we keep only issues on Github.

**Closed by stefanneculai** 2016-05-26 09:19 UTC

**Comment by rblin081** [comment] 2016-05-26 13:48
Thanks Stefan, it was just a small thing that came up for our clients so
thought it was worth putting in the suggestion box.
