### ISSUE TITLE
Code View Not closing

### ISSUE THREAD

**Issue by atlcodecommandr** [froala/wysiwyg-editor#3036] opened 2018-08-25 13:32 UTC
When I turn on Code view it replaces the box with code like it should. but when I turn it off, It now shows the wysiwyg and the code view at the same time. 

<img width="851" alt="screen shot 2018-08-25 at 9 30 10 am" src="https://user-images.githubusercontent.com/2533686/44618739-bce4f280-a849-11e8-83b9-7242cbed7f67.png">

**Comment by stefanneculai** [comment] 2018-09-03 13:37
@atlcodecommandr do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by stefanneculai** [comment] 2018-10-04 10:30
I am closing this as we couldn't reproduce it and we haven't got more details. Would be happy to look into it as soon as we get more details.

**Closed by stefanneculai** 2018-10-04 10:30 UTC
