### ISSUE TITLE
Copy/Paste Outlook email's content problem with froala-editor.pkgd.min.js on IE 11

### ISSUE THREAD

**Issue by khoanguyen** [froala/wysiwyg-editor#2508] opened 2018-01-22 20:26 UTC
##### Expected behavior.
Copying content from Microsoft Outlook's email (Word formatting) and Pasting into Froala editor should display the content correctly

##### Actual behavior.
The pasted content has space character omitted at random places. Check the screenshot below. The same problem is happening with the editor at https://www.froala.com/wysiwyg-editor 
**This only happens when using froala-editor.pkgd.min.js. After switching to froala-editor.js and includes the plugins manually, the problem didn't happen.**
![image](https://user-images.githubusercontent.com/824654/35240790-75073c72-ff69-11e7-8c87-5a0a7ff4fac4.png)

##### Steps to reproduce the problem.
**1. Creating an email which can cause the problem** 
- Open Outlook and new an Email which support rich formatting
- Open https://www.lipsum.com/ 
- Copy the following text from the lipsum.com page and paste it as is into the email 
![image](https://user-images.githubusercontent.com/824654/35242236-d63cd368-ff6d-11e7-914a-32a8f4617045.png)
- Send the email to an email address where you can retrieve it on Outlook (maybe send to yourself)

**2. Reproduce the bug with content of the email above**
- Create Web page to contain a Froala editor with froala-editor.pkgd.min.js
- Open the created page on IE 11
- Open the received email
- Copy (with Ctrl+C) the content of the email above
- Paste (with Ctrl+V) the content into the editor on IE 11

##### OS.
Windows 7, Windows 10

##### Browser.
Internet Explorer 11 (11.0.9600.18893) (Win 7)
Internet Explorer 11 (11.192.16299.0) (Win 10)

##### Misc.
Outlook - Microsoft Office Standard 2013
Froala Editor 2.7.3

For further information you can contact me via email at knguyen@ain1.com

Thanks and Regards.

**Comment by dianaprajescu** [comment] 2018-01-24 19:02
This might be a duplicate of #2491. Could you please paste the same content in Google Docs or any other place other than Outlook or the Froala Editor and let us know if it is pasted correctly or if it looks exactly the same as it is in the Froala Editor?

**Comment by khoanguyen** [comment] 2018-01-24 23:25
Thanks for you response.
Google Docs and Microsoft Word is fine.
I did some investigation and found a clue here.

In the screenshot, the top-left is Raw pasted content, which is in the clipboard before editor's cleaning process. I marked red X at the end of each line. The bottom-right is what you see on editor. The issues happening exactly at the positions those were marked red X in raw content.

![image](https://user-images.githubusercontent.com/824654/35362450-3d6cc3c4-011a-11e8-9c08-bd72f0885133.png)

**Comment by stefanneculai** [comment] 2018-01-25 12:18
@khoanguyen could you please put that HTML in a TXT file and send that file over to us? Thank you.

**Comment by khoanguyen** [comment] 2018-01-25 18:16
This is raw the content
[raw.txt](https://github.com/froala/wysiwyg-editor/files/1665126/raw.txt)

**Comment by khoanguyen** [comment] 2018-02-05 19:30
Is there any new update on this one?

**Comment by stefanneculai** [comment] 2018-02-27 21:28
@khoanguyen we couldn't replicate this yet. Could you please add the following code inside your app and let us know what you get in the console?

```js
$(selector).froalaEditor().on('froalaEditor.paste.beforeCleanup', function (e, editor, html) {
  console.log(html);
});
```

**Comment by khoanguyen** [comment] 2018-03-02 19:54
@stefanneculai The attachments are output from console.log(html) and screenshot of what I see on IE 11
![image](https://user-images.githubusercontent.com/824654/36918817-f81d19f0-1e0f-11e8-8757-5bab1eb2f478.png)

output.txt](https://github.com/froala/wysiwyg-editor/files/1776394/log.output.txt)

**Comment by stefanneculai** [comment] 2018-03-05 15:04
@khoanguyen thanks for all the details. The last commit should fix it.

**Closed** 2018-03-05 15:04 UTC

**Comment by khoanguyen** [comment] 2018-03-05 17:57
@stefanneculai Thanks for fixing this. How could I apply the fix to our websites? We're using 2.7.3

**Comment by stefanneculai** [comment] 2018-03-05 18:17
You could download the latest 2.7.6-dev from Github or wait the official release for 2.7.6.

**Comment by khoanguyen** [comment] 2018-03-05 20:17
Do you have a release date for 2.7.6 so that we will have a plan for our release as well ?

Thanks and Regards.
