### ISSUE TITLE
Make the new paragraph "escape" the formatting of the previous paragraph

### ISSUE THREAD

**Issue by dgroh** [froala/wysiwyg-editor#2963] opened 2018-07-16 14:58 UTC
**Expected behavior.**
When pressing Enter a new paragraph is created. I want the paragraph to be clean (with no formatting kept from the previous paragraph).

**Actual behavior.**
If the previous paragraph is bolded the newly created paragraph will also be bolded. It's the same with underline, italic, font-color and so on.

Does an option exist to make the new paragraph "escape" the formatting of the previous paragraph?

Thank you!

https://github.com/froala/wysiwyg-editor/issues/2807

**Comment by stefanneculai** [comment] 2018-07-16 16:26
Closing this as a duplicate of #2807.

**Closed by stefanneculai** 2018-07-16 16:26 UTC
