### ISSUE TITLE
image resizer position problem (IE11)

### ISSUE THREAD

**Issue by woro14** [froala/wysiwyg-editor#2946] opened 2018-07-09 09:17 UTC
##### Expected behavior.
Image resizer / cursor position like in Firefox

##### Actual behavior.
Image resizer positioned wrong
![grafik](https://user-images.githubusercontent.com/8413503/42441320-261ab606-8368-11e8-8573-8df4928eddab.png)

##### Steps to reproduce the problem.
go to https://www.froala.com/wysiwyg-editor
select the image. 
switch from inline to break text. 
unselect the image.
select the image.

##### OS.
Windows 10 

##### Browser.
IE11 (11.112.17134.0)

**Comment by stefanneculai** [comment] 2018-10-01 12:58
Duplicate of #2801

**Closed by stefanneculai** 2018-10-01 12:58 UTC
Labels: bug
