### ISSUE TITLE
Use Vanilla JS instead of Jquery

### ISSUE THREAD

**Issue by marek-hanzal** [froala/wysiwyg-editor#871] opened 2015-10-22 06:48 UTC
Chrome 45, Windows 8.1.

We've created Froala around common `<div>` (without textarea) - something like `$('.rich-text').froalaEditor()`.

Open debug panel to see DOM tree (it works in Chrome, in FF) and type something in editor; whole editor content will be updated, all nodes are getting `id=null`. Even in common setup, even on your [web page](https://www.froala.com/wysiwyg-editor/v2.0/). This "feature" isn't happening with [older Froala](https://www.froala.com/wysiwyg-editor).

**Comment by stefanneculai** [comment] 2015-10-23 15:21
Not so sure about how to reproduce it. Could you please provide few more details?

**Comment by marek-hanzal** [comment] 2015-10-26 08:29
Recorded Chrome 45 on Windows 8.1.

See dev. tools - Froala's content are updating all nodes, even when clicking into editor. (using v2.0)

![screen](https://cloud.githubusercontent.com/assets/13855126/10724272/749b7c0c-7bc3-11e5-884c-0bc4944009af.gif)

This is behavior of older version:
![screen2](https://cloud.githubusercontent.com/assets/13855126/10724327/fc1676fa-7bc3-11e5-841e-e13a65362c6b.gif)

Both Froalas are from your web :).

Same on Firefox 41.0.2.

**Comment by stefanneculai** [comment] 2015-10-26 10:57
This is happening because we're using some jQuery queries and Sizzle is adding some markups. I don't see why this is a problem.

**Comment by marek-hanzal** [comment] 2015-10-26 11:11
More content, more performance gain. Question is, is neccessary to update whole document even on mouse click?

**Comment by stefanneculai** [comment] 2015-10-26 11:14
We don't update the content, but just do some jQuery find queries on block tags ('p', 'h1', 'h2', etc.). jQuery is using Sizzle which adds some IDs to the tags and then removes them and that's why you see them as being updated. On long term we plan to remove jQuery and use vanilla JS. Definitely doing this will increase performance. I will mark this as enhancement for now.

**Comment by marek-hanzal** [comment] 2015-10-26 11:43
Ok, its more cleaner now, thank you :).

**Comment by stefanneculai** [comment] 2015-11-13 22:43
I am closing this for now. We'll replace jQuery with Vanilla JS at a point, but don't know exactly when.

**Closed by stefanneculai** 2015-11-13 22:43 UTC
Labels: enhancement

**Comment by Predjo** [comment] 2016-05-19 13:38
@stefanneculai Have you got a date of the VanillaJS implemntation. Its the only thing holding us back from using Froala.

**Comment by lochstar** [comment] 2016-05-30 23:42
Would also like a jQuery-free version.

**Comment by patadv** [comment] 2017-11-09 19:04
Is this still something that is happening? This issue was now closed 2 years ago with no indication of a jQuery-free Froala.

**Comment by marek-hanzal** [comment] 2017-11-09 20:51
Whoaw, such long time when I was doin this...

**Comment by NinioDev** [comment] 2018-12-11 20:40
same here, we're a paid customer, and Froala is the only library we use with a jQuery depedency, any plans to move to vanilla JS? I have seen there is an open idea, any time estimation?

**Comment by stefanneculai** [comment] 2018-12-13 11:49
We're working on it: https://wysiwyg-editor-roadmap.froala.com/public/ideas/3597. Things will most likely get hot around the end of Q1 2019.
