### ISSUE TITLE
Custom uri at character is prefixed with mailto:

### ISSUE THREAD

**Issue by xmedeko** [froala/wysiwyg-editor#3724] opened 2019-11-01 15:01 UTC
##### Actual behavior.
I have added a `ssh:` schema to `FroalaEditor.LinkProtocols`. When I enter URI with at sign, e.g. `ssh:user@server.com`, then it's prefixes with `mailto:` i.e. `mailto:ssh%3Asome@other.com`.

See also #3702

##### Expected behavior.
Do not prefix URIs in `FroalaEditor.LinkProtocols`

##### Editor version.
v3.0.5

##### Browser.
Electron, Chrome

**Comment by casualuser** [comment] 2019-11-01 15:39
Hello,

So https://github.com/froala/wysiwyg-editor/issues/3702 in most cases will be fixed in upcoming 3.0.7
As for this specific issue - I can't reproduce it at the moment
Please tweak this fiddle to let me find out what's the case https://jsfiddle.net/womjoy/6fvcdemL/

**Comment by xmedeko** [comment] 2019-11-02 08:23
Your fiddle shows the problem. Create a new link by Froala (not HTML) - CTRL + K, insert link `ssh:someone@awesome.dev`. Then edit the link and it's changed to `mailto:ssh%3Asomeone@awesome.dev`.

**Comment by kapil2704** [comment] 2019-11-04 14:37
Has been fixed for v3.0.8

**Closed by kapil2704** 2019-11-04 14:37 UTC
Labels: bug, version 3, waiting-details

**Comment by xmedeko** [comment] 2020-01-22 19:21
@kapil2704 I have tried v3.1.0 and the bug is still there.

**Comment by xmedeko** [comment] 2020-05-01 14:53
@kapil2704 Seems fixed in 3.1.1, thanks.
