### ISSUE TITLE
Github url issue

### ISSUE THREAD

**Issue by electroheadfx** [froala/wysiwyg-editor#1924] opened 2017-04-20 16:06 UTC
##### Expected behavior.
src="//www.youtube.com/embed/ID?wmode=opaque"

##### Actual behavior.
src="//www.youtube.com/embed/ID ?wmode=opaque"
A space is added before ?, it broke youtube video connection

##### Steps to reproduce the problem.
Enter a youtube video URL in froala editor

##### OS.
macOs Sierra

##### Browser.
Safari 10.1

**Comment by stefanneculai** [comment] 2017-04-24 09:02
We cannot reproduce it. Could you please send more details. What URL are you using? Where are you pasting it?

**Comment by electroheadfx** [comment] 2017-04-24 09:23
Hey Stefan, here the URL : 
http://cru2vie.org/blog/Test
To see the page you need to log with the account I sent you via email.

You can edit the froala test here in admin :
http://cru2vie.org/blog/admin/post/add/70

thanks

**Comment by stefanneculai** [comment] 2017-04-24 09:31
Closing this here and we're going to discuss via email.

**Closed by stefanneculai** 2017-04-24 09:31 UTC
Labels: cannot-reproduce
