### ISSUE TITLE
[BUG] br tag was inserted where paste some code!

### ISSUE THREAD

**Issue by itbdw** [froala/wysiwyg-editor#1874] opened 2017-03-27 06:52 UTC
##### Expected behavior.
br tag was inserted where paste some code!

##### OS.
Mac OS

##### Browser.
Chrome

**Comment by stefanneculai** [comment] 2017-03-27 07:47
Closing this because steps to reproduce were not provided.

**Closed by stefanneculai** 2017-03-27 07:47 UTC
