### ISSUE TITLE
Edit video popup not showing

### ISSUE THREAD

**Issue by emeryowa** [froala/wysiwyg-editor#3284] opened 2019-02-08 09:13 UTC
##### Expected behavior.
When selecting video edit video popup should show
##### Actual behavior.
No popup shows up when selecting edit video

##### Steps to reproduce the problem.
Initialize Froala editor with `videoEditButtons` setting set to `['videoReplace', 'videoRemove']`
Insert a video. (I inserted video from YouTube)
Select video in Froala editor
No edit popup shows up
https://jsfiddle.net/5Lm4uwzk/

When you set `videoEditButtons` setting to default as mentioned [here](https://www.froala.com/wysiwyg-editor/docs/options#videoEditButtons) it works

##### OS.
MacOS Mojave 10.14.2

##### Browser.
Chrome 71.0.3578.98

##### Recording.
See jsfiddle https://jsfiddle.net/5Lm4uwzk/

**Comment by stefanneculai** [comment] 2019-02-08 16:03
Duplicate of #3283

**Comment by emeryowa** [comment] 2019-02-18 10:06
@stefanneculai This issue still occurs after upgrading to 2.9.3 
https://jsfiddle.net/Lmoysw5t/6/

So it doesn't seem like a duplicate of https://github.com/froala/wysiwyg-editor/issues/3283, since that one is fixed now

**Closed** 2019-02-28 10:01 UTC
Labels: bug
