### ISSUE TITLE
Fixed-height wysiwyg - selected image & scroll: didn't change its position

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1099] opened 2016-03-02 14:08 UTC
I have fixed-height wysiwyg.

And if i select image there and scroll textarea, image selector position isn't changing:

![Image of wysiwyg](http://i.imgur.com/MuDZwMM.png)

**Comment by stefanneculai** [comment] 2016-03-02 14:14
Have you set the height using the editor option?

PS: please follow the issue template when reporting one.

**Comment by kotmatpockuh** [comment] 2016-03-03 08:27
Yes, i set it using option.

**Comment by stefanneculai** [comment] 2016-03-03 10:18
We cannot reproduce it on https://www.froala.com/wysiwyg-editor/docs/examples/predefined-height which uses the height option as it should. I believe you're doing something wrong. I am closing this for now. If you could make a jsFiddle to reflect the problem then we could definitely look over it.

**Closed by stefanneculai** 2016-03-03 10:18 UTC

**Comment by kotmatpockuh** [comment] 2016-03-10 14:33
@stefanneculai sorry, maybe U have any plunker with installed froala wysiwyg, so i will try to reproduce this bug and show you?

**Comment by stefanneculai** [comment] 2016-03-10 14:54
Unfortunately, we don't have any, only a jsFiddle: https://jsfiddle.net/froala/q79n2udx/

**Comment by javeriaanwer** [comment] 2017-12-11 09:18
I am facing same issue, but it's occurring after I enabled iframe. but its only happening in Chrome. 
please check this: https://codepen.io/Javeria_Anwer/pen/eyOWdR.

**Comment by stefanneculai** [comment] 2017-12-13 15:56
@javeriaanwer could you please make a recording to highlight the issue?

**Comment by javeriaanwer** [comment] 2017-12-21 06:37
you can see below recordings I did on chrome and firefox. 
[bugonfirefox.zip](https://github.com/froala/wysiwyg-editor/files/1578163/bugonfirefox.zip)

[bug.zip](https://github.com/froala/wysiwyg-editor/files/1578162/bug.zip)

**Comment by javeriaanwer** [comment] 2017-12-29 04:10
Hi,

I am still waiting for your response.
