### ISSUE TITLE
Editor scrolls to bottom on enter/backspace

### ISSUE THREAD

**Issue by SquareBeard** [froala/wysiwyg-editor#3677] opened 2019-09-24 13:10 UTC
##### Expected behavior.
The editor should scroll to keep the cursor visible.

##### Actual behavior.
The editor scrolls to the bottom regardless of the cursor position.

##### Steps to reproduce the problem.
Hit enter or backspace inside the first paragraph.
https://jsfiddle.net/340y5rjs/1/

##### Editor version.
v3.0.5

##### OS.
Windows

##### Browser.
Chrome

**Comment by SquareBeard** [comment] 2019-10-22 09:34
Could this be prioritized please ?
It makes the editor completely useless right now.

Thank you.

**Comment by MansaYzu** [comment] 2020-01-14 10:02
same problem too :<

**Comment by SquareBeard** [comment] 2020-01-15 12:34
Still buggy in v3.1.0

**Comment by vpekarek** [comment] 2020-03-04 14:27
Same problem in v3.1.0, but can't simulate it on jsfiddle. Looks like it is hapening only when the content is loaded from DB.

**Comment by SquareBeard** [comment] 2020-05-12 11:06
It's been five months and this critical bug is still not fixed. How is this possible for a commercial product ? I feel like I paid for something I can't use.

@vpekarek It is reproducible in jsfiddle, I've posted a link in my first post. Nothing to do with a database.

**Comment by vpekarek** [comment] 2020-05-12 11:10
Can somebody from Froala say a date when it will be fixed? Our clients are not happy about that. We are not happy about that. 
It is like we bought a car witch jumps back every time we want to accelerate.

**Comment by Chitaric** [comment] 2020-09-29 08:27
This problem is actual on v3.2.2

Testing on Firefox and Google Chrome

Steps to reproduce this bug
- Enter so much lines of text that the visible area of the editor is larger than the window height
- Press 'Enter' button in editor area :)

Problem code was found in enter event listener (froala_editor.js)
In minified file it like looks as `u.$oel[0].offsetHeight > u.o_win.innerHeight && u.o_win.scroll(0, u.$oel[0].scrollHeight)`

**Comment by danchaseCTS** [comment] 2020-10-30 20:21
This is also happening to be, can't wait for it to be fixed. I want the editor to grow as you type, no scrolling. For now I'm going to have to set a height - but what makes everything so difficult, is that a fixed height (or even using calc on vh) doesn't work so well from a responsive perspective, because it doesn't behave against it's container. This particular issue really needs fixed.

**Comment by sattes-faction** [comment] 2021-03-01 09:34
Any update on that? Still no feedback here. It's still broken and a really annoying issue.

**Comment by SquareBeard** [comment] 2021-03-01 11:32
They obviously don't care.
We got tricked into renewing the license, but that was the last time.
We already switched to another editor with great success and the complaints from our clients dropped.

**Comment by vpekarek** [comment] 2021-03-01 11:35
@SquareBeard  Can I ask you to what editor you switched for? Thinking about the same.

**Comment by sattes-faction** [comment] 2021-03-18 11:31
I asked the support about this and they said it's done in the next sustaining cycle (released planned in the next few months).

**Comment by dannyh79** [comment] 2021-03-24 09:03
> @SquareBeard Can I ask you to what editor you switched for? Thinking about the same.

@SquareBeard I'd like to know the editor you switched for as well....

**Comment by sattes-faction** [comment] 2021-06-08 06:39
any news on this?

**Comment by ilyaskarim** [comment] 2022-06-29 18:47
Fixed in V4.0.4: https://froala.com/wysiwyg-editor/changelog/#4.0.4

**Closed by ilyaskarim** 2022-06-29 18:47 UTC
Labels: bug, version 3
