### ISSUE TITLE
Froala at.js integration issue

### ISSUE THREAD

**Issue by NathanDubord** [froala/wysiwyg-editor#2171] opened 2017-08-30 17:13 UTC
##### Expected behavior.
https://www.froala.com/wysiwyg-editor/examples/at-js

Span that wraps the mention.
```<span class="atwho-inserted" data-atwho-at-query="@">@Jacob</span>```

##### Actual behavior.
```<span class="atwho-inserted" contenteditable="false" data-atwho-at-query="@">@Jacob</span>```

##### Steps to reproduce the problem.
Installed latest at.js and froala.

Froala config:
```
this.el.on('froalaEditor.initialized', function(e, editor) {
    editor.$el.atwho(config);

    editor.events.on('keydown', function(e) {
	if(e.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
	    return false;
	}
    }, true);
}).froalaEditor({
    language: window.__LANGUAGE,
    heightMin: 200,
    toolbarButtons: buttons,
});
```

at.js config:
```
let config = {
    at: '@',
    data: names,
    displayTpl: '<li>${name} <small>${email}</small></li>',
    limit: 100
};
```

Mentions are getting contenteditable="false" for some reason.

##### OS.
OS X El Capitan

##### Browser.
Chrome v.60

**Comment by stefanneculai** [comment] 2017-08-30 17:14
Duplicate of #2166

**Closed by stefanneculai** 2017-08-30 17:14 UTC
