### ISSUE TITLE
Pasting HTML content with line breaks adding paragraph tags

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#504] opened 2015-03-26 22:00 UTC
Is this intended behavior?

I'm looking at a webpage that looks like this. (Ignore the content of the message even though it seems related)
![screenshot 2015-03-26 14 58 03](https://cloud.githubusercontent.com/assets/97612/6858038/a6b1f476-d3c8-11e4-93fd-c2b205eadbbc.png)

Which has HTML with simple `<br>` line breaks (not paragraph tags):

![screenshot 2015-03-26 15 01 37](https://cloud.githubusercontent.com/assets/97612/6858088/07a07c12-d3c9-11e4-8952-091b7fe49103.png)

When copying the webpage content and pasting into Froala editor it appears like this with paragraphs:

![screenshot 2015-03-26 14 58 18](https://cloud.githubusercontent.com/assets/97612/6858049/c10e73e4-d3c8-11e4-85ba-87b338677a6e.png)

![screenshot 2015-03-26 14 58 22](https://cloud.githubusercontent.com/assets/97612/6858054/c7061db0-d3c8-11e4-86ed-02a121343113.png)

I would have expected it to have `<br>`s instead of `<p>`s -- especially since I'm using `paragraphy: false`.

**Comment by Dobbler** [comment] 2015-03-29 13:30
Same problem for me with br being removed from a li. It's part of an accordion (Foundation 5.5) so it's causing loads of formatting issues. Paragraphy is false as well. An option to not remove br tags would be nice.

**Comment by stefanneculai** [comment] 2015-03-30 09:12
@philfreo I've tried to replicate it but with no success. Could you please provide the steps to replicate it?

@Dobbler please open a different issue - it doesn't seem to be related. Also, we'd need the steps to reproduce it. Thanks.

**Comment by stefanneculai** [comment] 2015-04-08 07:49
@philfreo could you please provide more details?

**Comment by stefanneculai** [comment] 2015-04-14 08:40
I am closing this issue because we cannot reproduce it. If we'll got enough details to reproduce it, we'll reopen it and investigate further.

**Closed by stefanneculai** 2015-04-14 08:40 UTC
Labels: cannot-reproduce
