### ISSUE TITLE
Copy-Paste from word loses color and font formatting 

### ISSUE THREAD

**Issue by danielwallace1** [froala/wysiwyg-editor#1472] opened 2016-08-20 22:07 UTC
##### Expected behavior.

Colors and fonts should remain
##### Actual behavior.

Colors and fonts are lost
##### Steps to reproduce the problem.

Copy word document with colors and/or fonts and paste in editor
##### OS.

windows 7
##### Browser.

chrome 52

**Comment by stefanneculai** [comment] 2016-11-08 15:09
I am closing this because it will be implemented as feature which adds the possibility to keep advanced formatting on paste.

**Closed by stefanneculai** 2016-11-08 15:09 UTC
Labels: feature-request

**Comment by maverick42** [comment] 2016-12-03 10:40
+1

**Comment by pelizza** [comment] 2017-02-16 16:39
+1

Hey @stefanneculai , any news on this one?

Thanks!

**Comment by ingpdw** [comment] 2017-05-22 08:50
+1

**Comment by stefanneculai** [comment] 2017-05-22 08:51
@maverick42 @pelizza @ingpdw please make sure you are using the latest 2.6.0 version.

**Comment by pelizza** [comment] 2017-05-22 12:43
It's working fine on latest versions! Thanks!

**Comment by maverick42** [comment] 2017-05-22 12:59
Hi,
very good work ! Many people will be happy :) !

Frédérik

**Comment by mkerkeni** [comment] 2017-10-04 14:05
I reproduce the problem in IE11

**Comment by stefanneculai** [comment] 2017-10-05 15:59
@mkerkeni we would be happy to look into if you can send us the document you're pasting from. Thanks in advance.

**Comment by mkerkeni** [comment] 2017-10-05 17:35
![capturefroala](https://user-images.githubusercontent.com/13117542/31241507-ed424e70-a9fb-11e7-9d29-512927446eee.PNG)
Thank you for your response. 
You will find the word file and the result in IE11.
[froala.docx](https://github.com/froala/wysiwyg-editor/files/1360306/froala.docx)

**Comment by SwapnilMane** [comment] 2018-02-14 06:37
I am facing the same issue in IE11
Whereas in chrome it is working fine.
In IE11 it loses font, size and color of the text copied.

[Meeting notes (1).docx](https://github.com/froala/wysiwyg-editor/files/1722895/Meeting.notes.1.docx)

**Comment by stefanneculai** [comment] 2018-03-01 14:38
@SwapnilMane are you facing this on our website as well?

**Comment by SwapnilMane** [comment] 2018-03-02 03:51
Yes, I tried on your website using my IE browser.

**Comment by stefanneculai** [comment] 2018-03-02 19:21
@SwapnilMane are you getting the Word Paste modal?

**Comment by amerrnath-murugan-E0711** [comment] 2018-04-26 12:13
Any update on this issue

**Comment by SwapnilMane** [comment] 2018-04-26 12:16
This issue is only regarding to IE browser.


[image: Headfitted Solutions Pvt Ltd] <http://www.headfitted.com/>


*SWAPNIL B. MANE* / SOFTWARE ENGINEER
swapnil@headfitted.com / +91-9403968396

Headfitted Solutions Pvt Ltd
+91 20 6410 4444
C 904, Pune IT Park, Off Aundh RoadPune, Maharashtra
http://www.headfitted.com
