### ISSUE TITLE
Indentation issue in V3

### ISSUE THREAD

**Issue by skarthikeyan96** [froala/wysiwyg-editor#4089] opened 2020-11-09 10:29 UTC
##### Expected behavior.
(Describe expected behaviour here)
When we click on increase indent , it should not add the bullet point.

##### Actual behavior.
(Describe actual behaviour here)
It is adding the bullet point list.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

Add a text and try indentation. Bullet point is getting added in front of them.

https://jsfiddle.net/froala/s2qfapxg/

##### Editor version.
If you don't know it, please see https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717049-How-can-I-find-my-editor-version-.

v3.2.3

##### Browser.
(Browser name an version here)

All Major browser

**Comment by skarthikeyan96** [comment] 2020-11-10 06:41
blob:https://froala.com/828477d1-7ef4-4fc8-8ccd-f15599625594

**Comment by mikesul** [comment] 2020-11-20 13:01
We were hit by this as well. It appears that it is some sort of intentional change in 3.2.3 as it's related to the addition of the `_indentListStyleTypeNone` and `_outdentListStyleTypeNone` methods to the list plugin. We've worked around the issue by modifying the code to not call these methods.

Aside from the fact that this is buggy and actually seems to add 2 lists, it's a pretty big semantic difference from applying `margin-left` to shifting to a list with no visible bullet point. There's no mention of a related change in the changelog, so if this is to be kept, an option to maintain the existing behavior would be appreciated.

**Comment by Krisell** [comment] 2020-11-22 09:05
We're experiencing the same issue. Here's an example on your website:

The only action between these images is a click on the indent button:

![image](https://user-images.githubusercontent.com/25909128/99899501-1dbe3800-2caa-11eb-9935-bcb87107b08e.png)

![image](https://user-images.githubusercontent.com/25909128/99899508-2dd61780-2caa-11eb-99c7-628a40557a42.png)

**Comment by ftairs** [comment] 2020-11-23 22:37
Our team is also experiencing this issue on 3.2.3.

Expected behavior: Selected line or text is indented using either a class or a style attribute.

Actual behavior: Selected line has a style attribute added, with no way to remove via the UI. While the previous element is turned into a list.

<p>Test</p>
<p>Test</p> <--want to indent this line

becomes:

<p><ul><li style="list-style-type: none;"><ul><li>Test<br></li></ul></li></ul></p>
<p style="margin-left: 20px;">Test</p> <--cannot be undone via indent/outdent

**Comment by sovanny** [comment] 2020-12-21 16:41
Still experiencing this on 3.2.5. Has anyone found a good workaround for the issue that doesn't modify the source code? Like a custom indent-button?

**Comment by eguchi-t** [comment] 2020-12-22 06:05
In `lists.min.js`, if element.tagName is not `OL`, it will create a `UL` element, add a `LI` under it, and then add the element to the `LI`, which seems to be wrong.  
We are also having trouble with this bug, so please fix it as soon as possible.

**Comment by 486** [comment] 2021-01-30 20:39
Encountered the same issue. This bug is glaringly obvious on the product's website, I'd recommend fixing it asap to not alienate potential new customers.

**Comment by CrazyClicker** [comment] 2021-04-21 07:55
Same issue with 3.2.6-1 and couldn't find a workaround.

**Comment by rutfin** [comment] 2021-06-01 06:54
I can still reproduce the same issue

**Comment by ilyaskarim** [comment] 2022-09-08 00:03
Fixed in V3.2.7

**Closed by ilyaskarim** 2022-09-08 00:03 UTC
