### ISSUE TITLE
Ctrl+B doesn't consistently turn bold off

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#3031] opened 2018-08-21 23:06 UTC
##### Expected behavior.
When a user is typing and uses the keyboard shortcut Ctrl+B to turn bold on, then types some bold text, then uses Ctrl+B to unbold, the button in the toolbar should turn "off" and when the user continues to type, the text should not be bold.

##### Actual behavior.
When a user is typing and uses the keyboard shortcut Ctrl+B to turn bold on, then types some bold text, then uses Ctrl+B to unbold, the button in the toolbar looks like it's going to turn bold off, but when the user continues to type, the text is still bold and the toolbar Bold button turns back on.

##### Steps to reproduce the problem.
See attached video for visual walkthrough.

Start typing some words.
Use the Ctrl+B keyboard shortcut to turn on Bold.
Type some bold words.
Use the Ctrl+B keyboard shortcut to turn off Bold.
Type more words.
Sometimes it will work and the Bold turns off, but most of the time it doesn't seem to work and you will continue to type in bold.

##### OS.
PC with Windows 10

##### Browser.
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

[bold doesn't turn off using keyboard shortcut.zip](https://github.com/froala/wysiwyg-editor/files/2308316/bold.doesn.t.turn.off.using.keyboard.shortcut.zip)

**Comment by chrisdeeming** [comment] 2018-08-31 10:43
This looks similar to #3047 and #2621.

#2621 was closed but we found other reproduction cases that are similar to this so I opened #3047.

**Comment by raerae13** [comment] 2018-08-31 14:35
I agree, this appears to be the same type of issue.

**Comment by stefanneculai** [comment] 2018-09-03 14:52
Closing as duplicate of #3047

**Closed by stefanneculai** 2018-09-03 14:52 UTC
