### ISSUE TITLE
Line breaks in <pre> still an issue.

### ISSUE THREAD

**Issue by tischler** [froala/wysiwyg-editor#669] opened 2015-08-28 21:37 UTC
https://github.com/froala/wysiwyg-editor/issues/340 is still currently an issue.

**Comment by stefanneculai** [comment] 2015-08-30 20:44
Should be fixed on master.

**Closed by stefanneculai** 2015-08-30 20:44 UTC

**Comment by inexuscore** [comment] 2016-02-12 13:57
has this issue been fixed?
I've upgraded my Froala assets (css, js etc.) just recently and I had to refactor my code base due to breaking API changes. I can't seem to get my head around this.
I have a custom button which when clicked, opens up a modal dialog and accepts a code snippet through a textarea element. When you press save, the editor is focused, the selection is restored and the code snippet is inserted with a markup like this:
```
<pre>
  <code class="js">
    $(function() {
      // document ready, initialize.
      alert('Welcome back general');
    });
  </code>
</pre>
```

As mentioned by other users previously, the line breaks are shown properly when you're in WYSIWYG mode, but when you call `$('.selector').froalaEditor('html.get', true);` the line breaks are gone. 

I'm not sure if this is caused by the `html.get` method. Maybe I need to replace the new line characters with something like `<br>` or `&#13;&#10;`, but that doesn't work.

Please review this issue and if its still out there let's fix it together.

**Comment by stefanneculai** [comment] 2016-02-12 14:02
@inexuscore Please make a jsFiddle for it.

**Comment by inexuscore** [comment] 2016-02-12 14:37
@stefanneculai Sure thing, I'm on it. Quick replies, you :+1:
