### ISSUE TITLE
image and video resize outline in iframe

### ISSUE THREAD

**Issue by tonipepperoni** [froala/wysiwyg-editor#1065] opened 2016-02-15 06:13 UTC
Think there's an issue when you click an image or a video and you have the typical video or image options popup, but then you perform a scroll, and the outline remains even though image/video is not visible.

**Comment by stefanneculai** [comment] 2016-02-15 10:50
We cannot reproduce it. Could you please make a recording and check you're using the master version?

**Comment by tonipepperoni** [comment] 2016-02-16 12:38
yes, i think it's also because i have set a pre-defined height also.

**Comment by tonipepperoni** [comment] 2016-02-16 12:38
will get you a screen dump and a fiddle soon

**Comment by stefanneculai** [comment] 2016-02-26 11:47
I am closing this because we cannot reproduce it. We'll reopen it if we get enough details.

**Closed by stefanneculai** 2016-02-26 11:47 UTC
Labels: cannot-reproduce

**Comment by tonipepperoni** [comment] 2016-03-01 05:12
Hey there, trying to get a codepen/fiddle for you. 

I think where I'm having issues is when I have a fullscreen editor, which does a html.set()

It only happens when there is a html.set() otherwise it works fine
