### ISSUE TITLE
Image Resizer box displaced from its position if image height is increased to Page Size 

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2846] opened 2018-05-25 05:38 UTC
##### Expected behavior.
image resizer box should be fixed on image

##### Actual behavior.
image resizer box (image holder i.e. fr-image-resize) moves forward from image position

##### Steps to reproduce the problem.
goto : https://codepen.io/anon/pen/QrXvme

1. move image to center.
2. drag image till froala container end.

you will see image toolbar appears at bottom of page which increases page size thus page scrollbar appears   and image resize box is slightly moved to right.

![image-pagesize](https://user-images.githubusercontent.com/25203829/40527661-12d99a96-6007-11e8-82b5-56bb1a71e0e5.gif)

##### OS.
Windows 10

##### Browser.
Firefox
Chrome
Edge
IE

##### Code
```
$('#editor').froalaEditor({	
        height:450                 
            });
```

**Comment by stefanneculai** [comment] 2018-09-20 12:29
It is reproducible in IE on Windows 7. Create a blank page only with the editor on it. Add an image, center it and resize the image until you get the scroll on the right. At this point, the resizer box would be positioned incorrectly.

**Comment by stefanneculai** [comment] 2018-10-01 12:50
Duplicate of #2801

**Closed by stefanneculai** 2018-10-01 12:50 UTC
Labels: bug
