### ISSUE TITLE
splittin up nested tags - obsolete just answered!

### ISSUE THREAD

**Issue by M-Knobloch** [froala/wysiwyg-editor#1556] opened 2016-10-11 09:46 UTC
Having
```
<article>
	<section>Section content</section>
</article>
```
enter on cursor position between "Section" and "content"
##### Expected behavior.
```
<article>
	<section>Section<p>&nbsp;</p>content</section>
</article>
```

##### Actual behavior.
```
<article>
	<section>Section&nbsp;</section>
	<section>content</section>
</article>
```

##### Steps to reproduce the problem.
Try it on your online froala instance

##### OS.
independant

##### Browser.
mozilla, chrome

**Comment by stefanneculai** [comment] 2016-10-11 11:36
Duplicate of #1554

**Closed by stefanneculai** 2016-10-11 11:36 UTC
