### ISSUE TITLE
Does not work for Japanese Keyboard on iOS

### ISSUE THREAD

**Issue by haithngn** [froala/wysiwyg-editor#2823] opened 2018-05-17 08:21 UTC
##### Expected behavior.
Insert Japanese character normaly

##### Actual behavior.
No character was insert to the Froala Editor

##### Steps to reproduce the problem.
- From safari open Froala Editor at Froala's Homepage
- Hit editor to active editor mode (show ios keyboard)
- Change ios Keyboard to Japanese if you are not using Japanese keyboard.
- Tap B (Bold) on the editor's toolbar.
- Press any Japanese key on the ios keyboard.
- Tap B (Bold) on the editor's toolbar to deactive Bold mode
- Tap U (Underscore)  on the editor's toolbar.
- Press any  Japanese key on the ios keyboard. ~~~~~> no character will insert into the editor.

##### OS.
ios 10.3

##### Browser.
Safari

I'm using the Froala enterprise version.
Thanks,

**Comment by stefanneculai** [comment] 2018-07-24 13:30
I think this might have been fixed in the version 2.8.4. I am not able to reproduce it on the current website version. Do you think you could check?

**Comment by stefanneculai** [comment] 2018-10-04 10:20
Closing this due to lack of response.

**Closed by stefanneculai** 2018-10-04 10:20 UTC
Labels: cannot-reproduce
