### ISSUE TITLE
Korean languages typing problem.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#747] opened 2015-09-17 02:08 UTC
Hello, Developers froala wysiwyg HTML editor :)

Today is trying to tell a story hard to explain. Maybe this will be my own problem. I to type in the following in the context of the spaces removed korean languages, there is a problem.

Froala Editor 2.0,rc.2
- OS X yosemite
- FireFox
- Korean Languages keys

Below it is confirmed something that is a problem.
- Froala Editor 1.2(No Problem Firefox)
- OS X: chrome, safari, Windows OS all browser 

And I found the cause of the problem.
$(br).remove() tags that are to be a problem for me.

froala editor to remove the [BR], [SPAN class = "fr-maker"] is why every time a key is pressed?
(Excluding options EnterBR, Shift Enter key)

```JAVASCRIPT
    /**
     * Map keyUp actions.
     */
    function _mapKeyUp () {
      // IME IE.
      if (IME) return false;
      if (!editor.selection.isCollapsed()) return false;

      // Remove BR from elements that are not empty.
      var brs = editor.$el.find(editor.html.blockTagsQuery()).andSelf().not('TD, TH').find(' > br');
      for (var i = 0; i < brs.length; i++) {
        var br = brs[i];

        var prev_node = br.previousSibling;
        var next_node = br.nextSibling;

        // Get the parent node.
        var parent_node = editor.node.blockParent(br) || editor.$el.get(0);

        if (prev_node && parent_node && prev_node.tagName != 'BR' && !editor.node.isBlock(prev_node) && !next_node && $(parent_node).text().replace(/\u200B/g, '').length > 0 && $(prev_node).text().length > 0) {
          editor.selection.save();
//          $(br).remove(); <- Here code.
          editor.selection.restore();
        }
      }
```

korean languages is different from any other language. Enter the characters in the key combination.

```
ㅇ + ㅏ + ㄴ + ㄴ + ㅕ + ㅇ = 안녕 (hello)
d + k + s + s + u + d = six key
```

The funny thing is the javascript events keypress that occurs when an input character does not occur until you no longer occurs when you type the first character to complete the sentence.

The timing of the next events occurs when a other language key or press the space key twice.

And OS X Firefox has a bug in the code space by removing below.(I'm not sure.)

```JAVASCRIPT
<p>안녕 /u200b
    <span class="fr-maker" ... > </span>
</p>
```

```JAVASCRIPT
editor.$el.find('.fr-marker').remove();

<p>안녕</p> <- remove space
```

[Questions]
It introduces the differences when you use the $(br).remove(). Below is the HTML code of input to the first code and the next code.

```HTML
#$(br).remove(); Call
#first code
<p>안녕하세요. Froala Editor /*(Here the editor focus)*/</p>
#next code
<p>
   <br>
</p>
```

```HTML
#$(br).remove(); Not Call
#first code
<p>안녕하세요. Froala Editor /*(Here the editor focus)*/
   <br>
</p>
```

press the Enter key in focus.(not Call)
```HTML
<p>안녕하세요. Froala Editor</p>
<p>
   <br>
</p>

<p>
   <br>
</p>
```

I think that even if this $(br).remove code is no problem.

**Comment by stefanneculai** [comment] 2015-09-17 08:01
Thanks for all the details. Unfortunately, I don't understand exactly which the problem is. Would it be possible for you to make a recording highlighting the issue?

**Comment by largeden** [comment] 2015-09-17 13:29
sorry, I do not speak English well.

#### korean languages bug
https://www.dropbox.com/s/6zdn3fjnd2tqwom/froalaeditor_korean_languages.mov?dl=0
http://jsfiddle.net/largeden/Lp8rwhpy/90

#### $(br).remove() // Map keyUp actions, code delete
https://www.dropbox.com/s/estv2iwjo4sf8si/froalaeditor_korean_languages_patch.mov?dl=0
http://jsfiddle.net/largeden/Lp8rwhpy/91

**Comment by stefanneculai** [comment] 2015-09-17 14:02
I managed to reproduce the issue at our end. We'll fix it shortly. Thank you for all the details.

**Comment by stefanneculai** [comment] 2015-09-24 15:05
It appears to be fixed in the meanwhile. Most probably it was an issue caused by restoring selection that we fixed few days ago. Could you please check?

**Comment by largeden** [comment] 2015-09-24 15:51
@stefanneculai 
No, the same results.
It can be solved by clearing the $(br).remove () in v2.0.0-rc.3.

b.selection.save(),a(e).remove(),b.selection.restore())
b.selection.save(),b.selection.restore())

**Comment by stefanneculai** [comment] 2015-09-24 15:53
@largeden please try clearing the cache from your browser. Initially it was working for me locally, but not on jsFiddle and clearing the cache was the way to go.

Removing the `$('br').remove()` is not a good solution.

**Comment by largeden** [comment] 2015-09-24 16:02
https://www.dropbox.com/s/5gwz81incqnl0pi/br_tag_remove.mov?dl=0

@stefanneculai 

Sorry, the same results...

**Comment by largeden** [comment] 2015-09-24 16:13
I respect your opinion.
This problem is very unique.
If the problem by removing the code, do not remove code.. :)

Thank you for trying.

**Comment by stefanneculai** [comment] 2015-09-24 16:14
I've tested this on Yosemite 10.10.5, Firefox 41.0 and couldn't replicate it. Could you please check what OS version and FF version do you have? Also just to confirm, have you tried using the latest master version?

Here is a recording I made for it. Am I missing something? https://www.dropbox.com/s/58w1pafxlzq3uri/Korean.mov?dl=0

**Comment by largeden** [comment] 2015-09-24 16:18
@stefanneculai 

i'm Firefox 41.0, i tried using the latest master version.

![screen shot 2015-09-25 at 01 17 22](https://cloud.githubusercontent.com/assets/5575931/10079117/3e81b82e-6323-11e5-9bcd-402d2f76f808.png)

**Comment by stefanneculai** [comment] 2015-09-24 16:23
Makes sense now. Thanks for all the details.

**Comment by stefanneculai** [comment] 2015-09-25 12:24
@largeden I believe we just nailed it with the last commit. Could you please try it now and let us know if any issue is still there. Appreciate all the effort!

**Comment by largeden** [comment] 2015-09-25 13:30
@stefanneculai 

Thank you very much!!
The problem has been resolved.

https://www.dropbox.com/s/9c9bzcngo5yp27c/space.mov?dl=0

**Comment by stefanneculai** [comment] 2015-09-26 11:34
:+1:

**Closed by stefanneculai** 2015-09-26 11:34 UTC
Labels: bug, v2-contest
