### ISSUE TITLE
On Windows, BIU formatting shortcuts are reset to on after switching them off and hitting space

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#2621] opened 2018-03-04 18:38 UTC
##### Steps to reproduce the problem.
https://youtu.be/lrxTRZGYfG8
https://youtu.be/MQYYtaY6MyE

> If I use Ctrl+B (or I / U) to start formatting, then Ctrl+B (or I / U) to end, then immediately hit the space bar, the formatting comes back.
> 
> It works fine when clicking the editor buttons, but not when doing it via the keyboard.

##### OS.
Windows only AFAIK

##### Browser.
Chrome (at least)

**Comment by stefanneculai** [comment] 2018-04-09 11:00
@chrisdeeming this appears to be fixed in version 2.7.6. We've checked in on Chrome in Windows 7, 8.1 and 10.

**Closed by stefanneculai** 2018-04-09 11:00 UTC

**Comment by belazor** [comment] 2018-04-09 11:52
Sadly this is still reproducible, although much less easily than before. See demo videos from your own website:

https://www.youtube.com/watch?v=O47NZ30b1L4
https://www.youtube.com/watch?v=W4WpfeRCSJY

**Comment by stefanneculai** [comment] 2018-04-09 11:54
@belazor what OS are you using?

**Comment by belazor** [comment] 2018-04-09 11:56
@stefanneculai Chrome (latest stable) on Windows 10 (latest stable)

**Comment by stefanneculai** [comment] 2018-04-09 12:07
We've double checked it again on Browser Stack virtual machines, as well as physical devices and couldn't see it happening. Just to confirm, you're doing: (1) CTRL + B, (2) type something, (3) CTRL + B, (4) SPACE, (5) type something else.

**Comment by belazor** [comment] 2018-04-09 12:12
That's correct.

However, unlike the previous version of Froala where it seemed like I had anywhere up to 750ms to hit the space bar and it would bring the formatting back (as timed with my phone stopwatch), now I have to be lightning quick.

My experience with JS development is limited, but if this was fixed through some other change, is it possible some form of event had a delay or something that was since removed or reduced that could potentially explain the existence of the issue and the difficulty of reproducing it?

**Comment by stefanneculai** [comment] 2018-04-09 12:13
We haven't made any changes to that. One thing you might want to check is if you have any Chrome/Windows extensions that might affect typing.

**Comment by IgnitedKitsune** [comment] 2018-04-12 23:48
If you select two or more text formats, type a little and then unselect some or all of them and type a single letter, at least one of them will light up again and stay selected. If you type an additional letter after that, the 'selected' formatting is not applied but instead unselected. If you actually wanted it to apply though, you'd first have to unselect and then reselect again before it actually works.

**Comment by IgnitedKitsune** [comment] 2018-04-12 23:54
It also appears the editor script isn't fast enough if you're a rapid key smasher. Unselecting all three text options and instantly pressing spacebar will still turn on at least a few of the options. https://gfycat.com/EarlyIllClingfish

**Comment by chrisdeeming** [comment] 2018-04-26 10:33
@stefanneculai I can reproduce what is mentioned in the last couple of comments. I can't quite reproduce what @belazor is reporting, though I'll keep trying, but I suspect the behaviour that I **can** reproduce should be similar.

I've made a video:
https://youtu.be/XOwH4xZ-Zkw

Depending on when you see this, it might actually appear quite fast. I've just asked YouTube to slow it down to 2x speed. You do have to be very fast to repro it, hence slowing it down so you can more clearly see the exact steps.

I recorded it in BrowserStack, and I've enabled KeyCastr so you can see the exact keys being pressed.

You'll see me type some normal text, then I hit Cmd + B, I, U type a word and then I hit Cmd + B, I, U again. You can see the toolbar buttons deactivate. I then hit space, the space key doesn't register either, which is weird. But when I start typing again, B I U are highlighted again.

Would you like me to create a new issue for this, or will you re-open the issue?
