### ISSUE TITLE
Paste `html` argument is empty using IE9

### ISSUE THREAD

**Issue by Rob89** [froala/wysiwyg-editor#660] opened 2015-08-24 10:27 UTC
I've been having great success with Froala - except for just one very subtle problem - spaces between words are occasionally removed when pasting... In order to get together a repro I added code to log the raw html of the pasted content. However this isn't working on IE9 (which is also where I seem to be losing the spaces):

``` javascript
$(someSelector).on('editable.onPaste', function (e, editor,  html) {
    var contentBucket = $('.js-pasted-content'),
          currentHtml = contentBucket.val() || '';
    
    contentBucket.val(currentHtml + '  [BEGIN PASTE]' + html + '[END PASTE]  ');
})
```

Using latest Chrome and FireFox I get the expected `'[BEGIN PASTE](Lots of Html)[ENDPASTE]'`. However, in IE9 I just get `'[BEGINPASTE][ENDPASTE]'` - that is to say that the content is missing. I have verified this by changing the function to log to the console where I see empty strings each time.

FWIW, I was using the IE9 on Windows 7 Virtual Machine available on [modern.ie](http://dev.modern.ie/tools/vms/windows/).

Please let me know if I can add any further details to help.

**Comment by Rob89** [comment] 2015-08-24 15:18
I've been able to get the `html` parameter populated by adding the following to the `registerPaste` function:

```javascript
this.$element.on("beforepaste", a.proxy(function () { 
     b.getIEversion() <= 10 && b.getIEversion() > 7 && this.beforePaste(); 
}, this))
```

This gives the correct paste behaviour in IE9 and 10 as far as I can tell. Basically, in the `paste` event the content has already been added to the document making the focus to `$pasteDiv` ineffective. It appears that `beforepaste` happens in time for the content to be intercepted.

**Comment by stefanneculai** [comment] 2015-08-24 15:32
Hi Rob! Are you using the master version?

**Comment by Rob89** [comment] 2015-08-24 17:19
Hi Stefan, thanks for getting back to me. I was using 1.2.8 which as far as I know is the latest stable version. I will try the master version tomorrow and report back.

**Comment by Rob89** [comment] 2015-08-25 07:42
Hi Stefan

I tried again today with the latest master version and can confirm that the html argument **is an empty string** in IE9 and IE10.

**Comment by Rob89** [comment] 2015-08-26 14:36
For the record I've tracked down the missing spaces for some users being caused by `&#13;` (`\r`) present in the html on the clipboard. This presents itself in IE9 and IE10 but not IE11 AFAICT. I can't reproduce the issue at all using a variety of VMs so I don't know if it's some exact combination of OS, Browser and MS Word version.

My "fix" which is reported as working by users previously having the missing spaces problem is simply:

``` javascript
editor.on('editable.onPaste', function (e, editor, html) {
    return html.replace(/(?:&#13;&#10;|&#10;|&#13;|\r\n|\r|\n)/g, ' ');
});
```

That is to say, replace all new line characters with a single space - I can imagine that might cause problems with other types of paste but we're mostly dealing with people copy pasting from MS Word. I would raise this as a separate issue but as I can't reproduce it, I don't think it's fair to expect you to!

**Comment by stefanneculai** [comment] 2015-08-26 16:05
Thanks for tracking this Rob. We'll give it a try ourselves to see how it goes.

**Comment by jmangelo** [comment] 2015-08-27 10:39
Hi, we're also experiencing issues caused by the same situation Rob mentioned. 

The `html` argument in `onPaste` event (IE9) is empty which then means it does not get processed correctly. This results in uncleaned HTML being added to the editor.

Do you have any news on the status of this issue?

**Comment by stefanneculai** [comment] 2015-08-27 10:40
We tried few hours ago to reproduce this without success. @Rob89 or @jmangelo could you provide more details about where you're copying from?

**Comment by jmangelo** [comment] 2015-08-27 10:47
In our scenario we're trying to copy some cells from an Excel spreadsheet, more specifically, a two by two table where each cell just has a simple number.

On IE 9 this is what gets added to the editor:
```html
<table style="width: 96pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0" width="128">
    <tbody>
        <tr style="height: 15pt;" height="20">
            <td style="border: 0px black; width: 48pt; height: 15pt; background-color: transparent;" height="20" width="64" align="right">1</td>
            <td style="border: 0px black; width: 48pt; background-color: transparent;" width="64" align="right">2</td>
        </tr>
        <tr style="height: 15pt;" height="20">
            <td style="border: 0px black; height: 15pt; background-color: transparent;" height="20" align="right">3</td>
            <td style="border: 0px black; background-color: transparent;" align="right">4</td>
        </tr>
    </tbody>
</table>
```

On IE 11 we get:
```html
<table width="128" border="0" cellspacing="0" cellpadding="0">
    <tbody>
        <tr height="20">
            <td width="64" height="20" align="right">1</td>
            <td width="64" align="right">2</td>
        </tr>
        <tr height="20">
            <td height="20" align="right">3</td>
            <td align="right">4</td>
        </tr>
    </tbody>
</table>
```
The styles are cleaned up on IE11 but not on IE9 because the pasted content goes straight to the editor and does not seem to be processed. From the investigations, the cause seems to be the issue reported by Rob.

**Comment by stefanneculai** [comment] 2015-08-27 10:48
Could you send the EXCEL file to us? It might depend a lot on the way the EXCEL file was created.

**Comment by jmangelo** [comment] 2015-08-27 10:55
I've sent you an email (email address on your profile page) containing the sample file used to get the results above.

**Comment by stefanneculai** [comment] 2015-08-27 10:55
:+1:

**Comment by Rob89** [comment] 2015-08-27 11:09
I have likewise sent you an email :smiley:

**Comment by stefanneculai** [comment] 2015-11-13 22:35
V2 no longer supports IE9, therefore I am closing this one.

**Closed by stefanneculai** 2015-11-13 22:35 UTC
